"use client";
import { useEffect, useState } from "react";
import { gradeTotal, letter, gradeComplete, prerequisiteMet, retrieveGuidance, STAGES } from "@/lib/cx-intelligence";
import { I, Av, Pill, Card, Kpi, Empty, Head, Btn, Seg, Bars, Donut, Ring, Legend, PAL, ago, when, downloadFile, toCSV, type ModuleProps, type Row, type Ctx } from "./ui";

const students = (c: Ctx) => c.kind("context").filter(s => s.type === "Student");
const canEdit = (c: Ctx, section: string) => c.data.viewer.educationAccess || (c.data.viewer.instructorSections || []).includes(section);

/* ================= Student 360 ================= */
function GradeCard({ c, g, s }: { c: Ctx; g: Row; s: Row }) {
  const [items, setItems] = useState<Row[]>(g.items || []), [reason, setReason] = useState("");
  useEffect(() => setItems(g.items || []), [g.version]); // eslint-disable-line react-hooks/exhaustive-deps
  const edit = g.status === "Draft" && canEdit(c, g.section), approver = c.data.viewer.gradeApprover, total = gradeTotal(items as any), weights = items.reduce((a, i) => a + Number(i.w || 0), 0);
  const course = c.kind("course").find(x => x.code === g.section);
  const lms = g.lms?.status, canvasStyle = c.data.lms?.style === "canvas";
  return <Card title={`${g.section} · ${course?.name || ""}`} actions={g.status === "Final" ? <Pill t="g"><I n="check" s={12} /> Final grading completed · integrated to the student record</Pill> : g.status === "Pending approval" ? <Pill t="a">Awaiting approval</Pill> : <Pill>Draft</Pill>}>
    <div className="hx-tbl"><table><thead><tr><th>Component</th><th>Weight</th><th>Score</th>{edit && canvasStyle && <th>Scholaris assignment ID</th>}</tr></thead><tbody>{items.map((i, k) => <tr key={k}><td>{i.n}</td><td className="num">{edit ? <input className="hx-num" type="number" min={0} max={100} value={i.w} onChange={e => setItems(items.map((x, j) => j === k ? { ...x, w: Number(e.target.value) } : x))} aria-label={`${i.n} weight`} /> : `${i.w}%`}</td>
      <td>{edit ? <input className="hx-num" type="number" min={0} max={100} value={i.score ?? ""} placeholder="—" onChange={e => setItems(items.map((x, j) => j === k ? { ...x, score: e.target.value === "" ? null : Number(e.target.value) } : x))} aria-label={`${i.n} score`} /> : <b className="num">{i.score ?? "—"}</b>}</td>
      {edit && canvasStyle && <td><input className="hx-num wide" value={i.scholarisComponentId || ""} onChange={e => setItems(items.map((x, j) => j === k ? { ...x, scholarisComponentId: e.target.value } : x))} aria-label={`${i.n} Scholaris assignment`} placeholder="required" /></td>}</tr>)}
      <tr><td><b>Weighted total</b></td><td className={weights !== 100 ? "bad" : ""}>{weights}%</td><td><b className="num big">{total ?? "—"} · {letter(total)}</b></td>{edit && canvasStyle && <td />}</tr></tbody></table></div>
    {g.status === "Final" && <p className="hx-muted small">Approved by {g.approvedBy} {ago(g.approvedAt)} · Scholaris Global Learning: <b className={lms === "Synced" ? "ok" : lms === "Failed" ? "bad" : ""}>{lms || "—"}</b>{g.lms?.reference ? ` · ref ${g.lms.reference}` : ""}{g.lms?.error ? ` · ${g.lms.error}` : ""}</p>}
    {g.status === "Pending approval" && <p className="hx-muted small">Finalized by {g.finalizedBy} {ago(g.finalizedAt)}. A different approver signs off before the grade is final.</p>}
    {g.reopenReason && g.status === "Draft" && <p className="hx-muted small">Reopened: {g.reopenReason}</p>}
    <div className="hx-row">
      {edit && <><Btn onClick={() => c.post({ action: "grade.save", contextId: s.id, section: g.section, items }, "Draft saved")} disabled={c.busy}>Save draft</Btn><Btn kind="pri" disabled={c.busy || weights !== 100 || !gradeComplete(items as any)} title={!gradeComplete(items as any) ? "Enter every score first" : ""} onClick={() => c.post({ action: "grade.finalize", contextId: s.id, section: g.section, items }, "Finalized and sent for approval")}><I n="check" /> Finalize for approval</Btn></>}
      {g.status === "Pending approval" && approver && <><Btn kind="pri" onClick={() => c.post({ action: "grade.approve", id: g.id }, "Final grading completed and recorded")} disabled={c.busy}><I n="shield" /> Approve & record{c.data.lms?.configured ? " + sync to Scholaris" : ""}</Btn><input value={reason} onChange={e => setReason(e.target.value)} placeholder="Reason to return" aria-label="Return reason" style={{ maxWidth: 220 }} /><Btn disabled={!reason.trim()} onClick={() => c.post({ action: "grade.return", id: g.id, reason }, "Returned to draft")}>Return</Btn></>}
      {g.status === "Final" && approver && <>{lms !== "Synced" && c.data.lms?.configured && <Btn onClick={() => c.post({ action: "grade.lms.retry", id: g.id })}><I n="refresh" /> Retry Scholaris sync</Btn>}<input value={reason} onChange={e => setReason(e.target.value)} placeholder="Reason for grade change" aria-label="Grade change reason" style={{ maxWidth: 240 }} /><Btn disabled={!reason.trim()} onClick={() => c.post({ action: "grade.reopen", id: g.id, reason }, "Grade change opened")}>Request grade change</Btn></>}
    </div>
  </Card>;
}
export function Student360({ c }: ModuleProps) {
  const list = students(c);
  const [tab, setTab] = useState("Overview"), [brief, setBrief] = useState(""), [nw, setNw] = useState<Row>({ name: "", reference: "", program: "", year: 1, email: "", advisor: "" });
  const s = list.find(x => x.id === c.student) || null;
  useEffect(() => { if (!c.student && list[0]) c.setStudent(list[0].id); }, [list.length]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => setBrief(""), [s?.id]);
  const step = (d: number) => { if (!list.length) return; const i = list.findIndex(x => x.id === s?.id); c.setStudent(list[(i + d + list.length) % list.length].id); };
  const edu = c.data.viewer.educationAccess;
  if (!s) return <><Head title="Student 360" sub="Everything about one student in one place." />
    <Card wide>{list.length ? <Empty>Select a student.</Empty> : edu ? <><p className="hx-muted">No student records yet. Add one, or load clearly labeled sample data for staging.</p><div className="hx-grid g3">{(["name", "reference", "program", "email", "advisor"] as const).map(k => <label className="hx-f" key={k}>{k[0].toUpperCase() + k.slice(1)}<input value={nw[k]} onChange={e => setNw({ ...nw, [k]: e.target.value })} /></label>)}</div><div className="hx-row"><Btn kind="pri" onClick={() => c.post({ action: "save", kind: "context", data: { ...nw, type: "Student" } }, "Student added")}>Add student</Btn><Btn onClick={() => c.post({ action: "sample.seed" }, "Sample data loaded")}>Load sample data</Btn></div></> : <Empty>Student records are limited to authorized registrars, administrators and instructors of record.</Empty>}</Card></>;
  const grades = c.kind("grade").filter(g => g.contextId === s.id);
  const sessions = c.kind("session").filter(x => x.contextId === s.id);
  const app = c.kind("applicant").find(a => a.name === s.name);
  const courses = c.kind("course");
  const views = c.data.events.filter(e => e.contextId === s.id && e.type === "context.accessed").length;
  const actions: Row[] = [...(s.holds || []).map((h: string) => ({ t: `Resolve hold: ${h}`, sev: "r" })), ...grades.filter(g => g.status === "Draft" && canEdit(c, g.section)).map(g => ({ t: `Finalize grades for ${g.section}`, sev: "a", tab: "Grades" })), ...grades.filter(g => g.status === "Pending approval").map(g => ({ t: `Approve grades for ${g.section}`, sev: "a", tab: "Grades" })), ...grades.filter(g => g.lms?.status === "Failed").map(g => ({ t: `Scholaris sync failed for ${g.section}`, sev: "r", tab: "Grades" })), ...(!(s.sections || []).length && s.status === "Active" ? [{ t: "Not registered for any course", sev: "a", tab: "Enrollment" }] : [])];
  const summarize = async () => { const r = await c.ai("student", `Program ${s.program}, year ${s.year}. GPA ${s.gpa || "n/a"}. Holds: ${(s.holds || []).join(", ") || "none"}. Sections: ${(s.sections || []).join(", ") || "none"}. Grades: ${grades.map(g => `${g.section} ${gradeTotal(g.items) ?? "incomplete"} (${g.status})`).join("; ") || "none"}. Open sessions: ${sessions.filter(x => x.status === "Open").map(x => x.subject).join(", ") || "none"}.`); setBrief(r?.text || `${s.name.split(" ")[0]} is a year-${s.year} ${s.program} student${s.gpa ? ` with a ${Number(s.gpa).toFixed(2)} GPA` : ""}. ${(s.holds || []).length ? `Holds: ${s.holds.join(", ")}.` : "No holds."} ${(s.sections || []).length ? `Enrolled in ${s.sections.join(", ")}.` : "Not registered this term."}`); };
  return <>
    <Head title="Student 360" sub="Switch students from the dropdown. Every record view is written to the audit log.">
      <label className="hx-inline-label">Student<select value={s.id} onChange={e => c.setStudent(e.target.value)} aria-label="Student">{list.map(x => <option key={x.id} value={x.id}>{x.name} · {x.reference}</option>)}</select></label>
      <Btn onClick={() => step(-1)} title="Previous student"><I n="back" /></Btn><Btn onClick={() => step(1)} title="Next student"><I n="fwd" /></Btn>
    </Head>
    {!edu && <div className="hx-note"><I n="lock" s={14} /> Showing students in your sections ({(c.data.viewer.instructorSections || []).join(", ") || "none"}).</div>}
    <div className="hx-hero"><div className="hx-row nowrap"><Av name={s.name} lg /><div><h2>{s.name} {s.sample && <Pill>Sample</Pill>}</h2><p>{s.program || "Program not set"} · Year {s.year} · {s.reference}</p><small>{s.email || "No email on file"} · Advisor {s.advisor || "—"}</small></div></div>
      <div className="hx-row wide-gap"><div className="hx-mini"><small>GPA</small><b>{s.gpa ? Number(s.gpa).toFixed(2) : "—"}</b></div><div className="hx-mini"><small>Sections</small><b>{(s.sections || []).length}</b></div><div className="hx-mini"><small>Open sessions</small><b>{sessions.filter(x => x.status === "Open").length}</b></div><div className="hx-mini"><small>Record views</small><b>{views}</b></div><Pill t={s.status === "Active" ? "g" : "a"}>{s.status}</Pill></div></div>
    <Seg value={tab} options={["Overview", "Grades", "Enrollment", "Sessions", "Actions"]} onChange={setTab} /><div className="hx-gap" />
    {tab === "Overview" && <div className="hx-grid g3"><Card title="Holds">{(s.holds || []).length ? s.holds.map((h: string) => <div className="hx-li" key={h}><Pill t="r">Hold</Pill><span className="hx-grow">{h}</span>{edu && <Btn kind="sm" onClick={() => c.post({ action: "save", kind: "context", id: s.id, data: { ...s, holds: s.holds.filter((x: string) => x !== h) } }, "Hold cleared")}>Clear</Btn>}</div>) : <Pill t="g">No holds</Pill>}</Card>
      <Card title="Application">{app ? <><p>Stage <b>{app.stage}</b></p>{Object.entries(app.docs || {}).map(([d, ok]) => <p key={d} className="small"><I n={ok ? "check" : "x"} s={12} /> {d}</p>)}</> : <p className="hx-muted">No admissions record linked.</p>}</Card>
      <Card title={<><I n="spark" /> Advising brief</>}><p className="hx-pre">{brief || "Generate a short brief for advising. Identification numbers are left out."}</p><Btn kind="vio sm" onClick={summarize} disabled={c.busy}><I n="spark" /> Summarize</Btn></Card></div>}
    {tab === "Grades" && <div className="hx-grid g2">{grades.filter(g => canEdit(c, g.section) || c.data.viewer.gradeApprover).map(g => <GradeCard key={g.id} c={c} g={g} s={s} />)}{!grades.length && <Card wide><Empty>No graded sections.</Empty></Card>}</div>}
    {tab === "Enrollment" && <Card wide><div className="hx-tbl"><table><thead><tr><th>Course</th><th>Schedule</th><th>Prerequisite</th><th>Seats</th><th /></tr></thead><tbody>{courses.map(x => { const inIt = (s.sections || []).includes(x.code), pre = prerequisiteMet(x, s.completed); return <tr key={x.id}><td><b>{x.code}</b> {x.name}<small>{x.instructor}</small></td><td><small>{x.days} · {x.mode}</small></td><td>{x.prereq ? <Pill t={pre ? "g" : "r"}>{pre ? `${x.prereq} ✓` : `needs ${x.prereq}`}</Pill> : "—"}</td><td className="num">{x.enrolled}/{x.cap}{x.wait ? ` · ${x.wait} waiting` : ""}</td><td>{edu ? inIt ? <Btn kind="sm" onClick={() => c.post({ action: "drop", contextId: s.id, course: x.code })}>Drop</Btn> : <Btn kind="sm pri" disabled={!pre} onClick={() => c.post({ action: "enroll", contextId: s.id, course: x.code })}>{x.enrolled >= x.cap ? "Join waitlist" : "Enroll"}</Btn> : inIt ? <Pill t="t">Enrolled</Pill> : null}</td></tr>; })}</tbody></table>{!courses.length && <Empty>No courses in the catalog. Add them in Admissions & Registration.</Empty>}</div></Card>}
    {tab === "Sessions" && <Card wide>{sessions.map(x => <div className="hx-li" key={x.id}><b className="hx-grow">{x.subject}</b><small>{when(x.startedAt)}</small><Pill t={x.status === "Resolved" ? "g" : "t"}>{x.status}</Pill><Btn kind="sm" onClick={() => { c.setSession(x.id); c.go("sessions"); }}>Open</Btn></div>)}{!sessions.length && <Empty>No sessions linked to this student.</Empty>}<Btn kind="sm" onClick={async () => { const r = await c.post({ action: "save", kind: "session", data: { contextId: s.id, subject: `Advising · ${s.name}`, persona: "Amara", channel: "Web" } }); if (r?.id) { c.setSession(r.id); c.go("sessions"); } }}><I n="plus" s={12} /> Start linked session</Btn></Card>}
    {tab === "Actions" && <Card wide>{actions.map((a, i) => <div className="hx-li" key={i}><span className={`hx-dot ${a.sev}`} /><span className="hx-grow">{a.t}</span>{a.tab && <Btn kind="sm" onClick={() => setTab(a.tab)}>Open</Btn>}</div>)}{!actions.length && <Empty>Nothing outstanding.</Empty>}</Card>}
  </>;
}

/* ================= Classroom ================= */
export function Classroom({ c }: ModuleProps) {
  const mine = c.data.viewer.instructorSections || [];
  const courses = c.kind("course").filter(x => c.data.viewer.educationAccess || mine.includes(x.code));
  const [code, setCode] = useState("");
  const course = courses.find(x => x.code === code) || courses[0];
  if (!course) return <><Head title="Classroom" /><Card wide><Empty>No sections assigned to you. Courses list you as instructor through their instructor email.</Empty></Card></>;
  const grades = c.kind("grade").filter(g => g.section === course.code), roster = students(c).filter(s => (s.sections || []).includes(course.code));
  const comps: string[] = grades[0]?.items?.map((i: Row) => i.n) || [];
  const avg = comps.map(n => { const v = grades.map(g => g.items.find((i: Row) => i.n === n)?.score).filter((x: unknown): x is number => typeof x === "number"); return v.length ? Math.round(v.reduce((a, b) => a + b, 0) / v.length) : 0; });
  const totals = grades.map(g => gradeTotal(g.items)).filter((x): x is number => x !== null);
  const classAvg = totals.length ? Math.round(totals.reduce((a, b) => a + b, 0) / totals.length) : null;
  const finalPct = grades.length ? Math.round(grades.filter(g => g.status === "Final").length / grades.length * 100) : null;
  const today = new Date().toLocaleDateString("en-US", { weekday: "short" });
  const todays = courses.filter(x => String(x.days).toLowerCase().includes(today.toLowerCase().slice(0, 3)));
  return <>
    <Head title="Classroom" sub="Your sections at a glance: today's classes, how the class is doing on each module, and where grading stands."><select value={course.code} onChange={e => setCode(e.target.value)} aria-label="Section">{courses.map(x => <option key={x.id}>{x.code}</option>)}</select></Head>
    <div className="hx-grid g31">
      <div className="hx-col">
        <Card title="Today's classes">{todays.map(x => <div className="hx-li" key={x.id}><span className="hx-stripe" /><div className="hx-grow"><b>{x.name}</b><small>{x.code} · {x.days} · {x.mode}</small></div><Btn kind="ghost sm" onClick={() => setCode(x.code)}><I n="fwd" /></Btn></div>)}{!todays.length && <p className="hx-muted">No classes scheduled for {today}.</p>}</Card>
        <Card title="Roster">{roster.map(s => { const g = grades.find(x => x.contextId === s.id), t = g ? gradeTotal(g.items) : null; return <div className="hx-li" key={s.id}><Av name={s.name} /><div className="hx-grow"><b>{s.name}</b><small>{t ?? "—"} · {letter(t)}{g && !gradeComplete(g.items) ? " · partial" : ""}</small></div><Pill t={g?.status === "Final" ? "g" : g?.status === "Pending approval" ? "a" : ""}>{g?.status || "—"}</Pill><Btn kind="ghost sm" onClick={() => { c.setStudent(s.id); c.go("student"); }}><I n="fwd" /></Btn></div>; })}{!roster.length && <Empty>No students enrolled.</Empty>}</Card>
      </div>
      <div className="hx-col">
        <Card title={`Learning curve · ${course.code}`} actions={<small>Class average per component</small>}>{comps.length ? <Bars labels={comps.map(n => n.split(" · ")[0])} series={[{ name: "Class average", values: avg, color: PAL[1] }]} fmt={v => `${Math.round(v)}`} /> : <Empty>No grade components yet.</Empty>}</Card>
        <div className="hx-grid g2">
          <div className="hx-stat orange"><Ring value={finalPct} color="#fff" size={72} label="Grades final" /><div><small>Grading status</small><b>{grades.filter(g => g.status === "Final").length}/{grades.length} final</b></div></div>
          <div className="hx-stat blue"><Ring value={classAvg} color="#fff" size={72} label="Class average" /><div><small>Class average</small><b>{classAvg ?? "—"}/100</b></div></div>
        </div>
        <Card title="Statistics"><div className="hx-grid g3 tight"><div className="hx-mini"><small>Enrolled</small><b>{course.enrolled}/{course.cap}</b></div><div className="hx-mini"><small>Waitlist</small><b>{course.wait}</b></div><div className="hx-mini"><small>Awaiting approval</small><b>{grades.filter(g => g.status === "Pending approval").length}</b></div></div></Card>
      </div>
    </div>
  </>;
}

/* ================= Admissions & Registration ================= */
export function Admissions({ c }: ModuleProps) {
  const [tab, setTab] = useState("Pipeline"), [nw, setNw] = useState({ name: "", program: "AS Network Security", email: "" }), [course, setCourse] = useState<Row>({ code: "", name: "", instructor: "", instructorEmail: "", cap: 30, prereq: "", days: "", mode: "Hybrid" }), [q, setQ] = useState(""), [chat, setChat] = useState<Row[]>([]), [over, setOver] = useState("");
  const apps = c.kind("applicant"), courses = c.kind("course"), edu = c.data.viewer.educationAccess;
  if (!edu) return <><Head title="Admissions & Registration" /><Card wide><Empty>Admissions records are limited to authorized registrars and administrators.</Empty></Card></>;
  const move = (id: string, stage: string) => c.post({ action: "applicant.move", id, stage }, `Moved to ${stage}`);
  const ask = async () => { if (!q.trim()) return; const text = q; setQ(""); const guide = retrieveGuidance(text, c.kind("knowledge") as any); const r = await c.ai("reply", `Persona: Amara (Friendly), admissions.\nApproved guidance:\n${guide.map(g => `- ${g.title}: ${g.excerpt}`).join("\n") || "- none matched"}\nApplicant: ${text}`); setChat([...chat, { me: text }, { ai: r?.text || guide[0]?.excerpt || "I don't have an approved answer for that yet. I've logged it so the admissions team can add one." }]); };
  return <>
    <Head title="Admissions & Registration" sub="Applicants move through the pipeline as their documents arrive. Drag cards between stages; decisions need a complete file."><Btn onClick={async () => { for (const a of apps.filter(a => Object.values(a.docs || {}).some(v => !v))) await c.post({ action: "applicant.remind", id: a.id }); c.toast("Reminders logged for every incomplete file"); }}><I n="send" /> Remind all incomplete</Btn></Head>
    <Seg value={tab} options={["Pipeline", "Course catalog", "Applicant FAQ"]} onChange={setTab} /><div className="hx-gap" />
    {tab === "Pipeline" && <><div className="hx-kan">{STAGES.map(st => <div key={st} className={`hx-kcol${over === st ? " over" : ""}`} onDragOver={e => { e.preventDefault(); setOver(st); }} onDragLeave={() => setOver("")} onDrop={e => { e.preventDefault(); setOver(""); const id = e.dataTransfer.getData("text/plain"); if (id) move(id, st); }}>
      <div className="hx-row between"><b>{st}</b><Pill>{apps.filter(a => a.stage === st).length}</Pill></div>
      {apps.filter(a => a.stage === st).map(a => { const missing = Object.entries(a.docs || {}).filter(([, v]) => !v).map(([k]) => k), done = Object.keys(a.docs || {}).length - missing.length; return <div key={a.id} className="hx-kcard" draggable onDragStart={e => e.dataTransfer.setData("text/plain", a.id)}><b>{a.name}</b>{a.sample && <Pill>Sample</Pill>}<small>{a.program}</small><div className="hx-bar"><i style={{ width: `${done / Math.max(1, Object.keys(a.docs || {}).length) * 100}%` }} /></div>
        {missing.length ? <div className="hx-docs">{missing.map(d => <button key={d} onClick={() => c.post({ action: "applicant.doc", id: a.id, doc: d }, `${d} received`)} title="Mark received"><I n="plus" s={10} /> {d}</button>)}</div> : <small className="ok">All documents in</small>}
        <div className="hx-row">{missing.length > 0 && <Btn kind="sm" onClick={() => c.post({ action: "applicant.remind", id: a.id })}>Remind</Btn>}{st !== "Enrolled" && <Btn kind="ghost sm" onClick={() => move(a.id, STAGES[STAGES.indexOf(st) + 1])}>Advance →</Btn>}</div></div>; })}
    </div>)}</div>
      <Card title="Add applicant"><div className="hx-row"><input value={nw.name} onChange={e => setNw({ ...nw, name: e.target.value })} placeholder="Full name" aria-label="Applicant name" /><input value={nw.email} onChange={e => setNw({ ...nw, email: e.target.value })} placeholder="Email" aria-label="Applicant email" /><select value={nw.program} onChange={e => setNw({ ...nw, program: e.target.value })} aria-label="Program">{["AS Network Security", "AS Cloud Computing", "BS Cybersecurity", "Network Security Certificate"].map(o => <option key={o}>{o}</option>)}</select><Btn kind="pri" disabled={!nw.name.trim()} onClick={async () => { if (await c.post({ action: "save", kind: "applicant", data: nw }, "Applicant added")) setNw({ ...nw, name: "", email: "" }); }}>Add</Btn></div></Card></>}
    {tab === "Course catalog" && <><Card wide><div className="hx-tbl"><table><thead><tr><th>Course</th><th>Instructor</th><th>Schedule</th><th>Prereq</th><th>Seats</th><th>Scholaris section ID</th><th /></tr></thead><tbody>{courses.map(x => <tr key={x.id}><td><b>{x.code}</b> {x.name}</td><td>{x.instructor}<small>{x.instructorEmail}</small></td><td><small>{x.days} · {x.mode}</small></td><td>{x.prereq || "—"}</td><td><div className="hx-row nowrap"><div className="hx-bar" style={{ width: 70 }}><i style={{ width: `${Math.min(100, x.enrolled / x.cap * 100)}%` }} /></div><small>{x.enrolled}/{x.cap}{x.wait ? ` · ${x.wait} waiting` : ""}</small></div></td><td><input className="hx-num wide" defaultValue={x.scholarisSectionId} onBlur={e => e.target.value !== (x.scholarisSectionId || "") && c.post({ action: "save", kind: "course", id: x.id, data: { ...x, scholarisSectionId: e.target.value } }, "Scholaris mapping saved")} aria-label={`${x.code} Scholaris section ID`} placeholder="—" /></td><td><Btn kind="sm" onClick={() => c.post({ action: "save", kind: "course", id: x.id, data: { ...x, cap: x.cap + 5 } }, "Five seats added")}>+5 seats</Btn></td></tr>)}</tbody></table>{!courses.length && <Empty>No courses yet.</Empty>}</div></Card>
      <Card title="Add course"><div className="hx-grid g4">{(["code", "name", "instructor", "instructorEmail", "prereq", "days"] as const).map(k => <label key={k} className="hx-f">{({ code: "Code", name: "Name", instructor: "Instructor", instructorEmail: "Instructor email", prereq: "Prerequisite", days: "Schedule" } as Row)[k]}<input value={course[k]} onChange={e => setCourse({ ...course, [k]: e.target.value })} /></label>)}<label className="hx-f">Capacity<input type="number" value={course.cap} onChange={e => setCourse({ ...course, cap: Number(e.target.value) })} /></label><label className="hx-f">Mode<select value={course.mode} onChange={e => setCourse({ ...course, mode: e.target.value })}>{["Hybrid", "Online", "On campus"].map(o => <option key={o}>{o}</option>)}</select></label></div><Btn kind="pri" disabled={!course.code || !course.name} onClick={() => c.post({ action: "save", kind: "course", data: course }, "Course added")}>Add course</Btn></Card></>}
    {tab === "Applicant FAQ" && <Card wide title="Ask Amara as an applicant would"><div className="hx-thread short">{chat.map((m, i) => <div key={i} className={`hx-bub ${m.me ? "me" : "ai"}`}>{m.me || m.ai}</div>)}{!chat.length && <p className="hx-muted">Answers come from approved admissions knowledge.</p>}</div><div className="hx-row nowrap"><input value={q} onChange={e => setQ(e.target.value)} onKeyDown={e => e.key === "Enter" && ask()} placeholder="What documents do I need?" aria-label="Applicant question" /><Btn kind="vio" onClick={ask} disabled={c.busy}><I n="spark" /> Ask</Btn></div></Card>}
  </>;
}

/* ================= Faculty Directory ================= */
export function Faculty({ c }: ModuleProps) {
  const fac = c.kind("faculty"), [q, setQ] = useState(""), [nw, setNw] = useState<Row>({ name: "", title: "Professor", dept: "Engineering", qual: "PhD", exp: 5, email: "" });
  const can = c.data.viewer.admin || c.data.viewer.educationAccess;
  const depts: Record<string, number> = {}; fac.forEach(f => depts[f.dept] = (depts[f.dept] || 0) + 1);
  const quals: Record<string, number> = {}; fac.forEach(f => quals[f.qual] = (quals[f.qual] || 0) + 1);
  const shown = fac.filter(f => !q || `${f.name} ${f.dept} ${f.title}`.toLowerCase().includes(q.toLowerCase()));
  return <>
    <Head title="Faculty Directory" sub="Staff records, teaching load, research output and department mix in one place."><Btn onClick={() => downloadFile("faculty-directory.csv", toCSV([["Name", "Title", "Department", "Qualification", "Experience", "Status", "Load", "Publications", "Email"], ...fac.map(f => [f.name, f.title, f.dept, f.qual, f.exp, f.status, f.load, f.pubs, f.email])]))}><I n="dl" /> Export CSV</Btn></Head>
    <div className="hx-kpis four"><Kpi label="Total faculty" value={fac.length} /><Kpi label="PhD faculty" value={fac.length ? `${Math.round((quals.PhD || 0) / fac.length * 100)}%` : "—"} tone="v" /><Kpi label="Research publications" value={fac.reduce((a, f) => a + (f.pubs || 0), 0)} tone="t" /><Kpi label="Avg teaching load" value={fac.length ? `${(fac.reduce((a, f) => a + (f.load || 0), 0) / fac.length).toFixed(1)} cr` : "—"} /></div>
    <div className="hx-grid g21">
      <Card title="Directory" actions={<input value={q} onChange={e => setQ(e.target.value)} placeholder="Search faculty" aria-label="Search faculty" style={{ width: 200 }} />}>
        <div className="hx-facgrid">{shown.map(f => <div key={f.id} className="hx-fac"><Av name={f.name} lg /><b>{f.name}</b><small>{f.title}</small><small className="dim">{f.dept}</small><dl><dt>Qualification</dt><dd>{f.qual}</dd><dt>Experience</dt><dd>{f.exp} yrs</dd><dt>Load</dt><dd>{f.load} cr</dd><dt>Status</dt><dd><Pill t={f.status === "Active" ? "g" : "a"}>{f.status}</Pill></dd></dl>{can && <Btn kind="sm" onClick={() => c.post({ action: "save", kind: "faculty", id: f.id, data: { ...f, status: f.status === "Active" ? "On leave" : "Active" } })}>{f.status === "Active" ? "Mark on leave" : "Mark active"}</Btn>}</div>)}</div>
        {!fac.length && <Empty>No faculty records yet.</Empty>}
        {can && <div className="hx-row" style={{ marginTop: 14 }}><input value={nw.name} onChange={e => setNw({ ...nw, name: e.target.value })} placeholder="Name" aria-label="Faculty name" /><select value={nw.title} onChange={e => setNw({ ...nw, title: e.target.value })} aria-label="Title">{["Professor", "Associate Professor", "Assistant Professor", "Lecturer"].map(o => <option key={o}>{o}</option>)}</select><select value={nw.dept} onChange={e => setNw({ ...nw, dept: e.target.value })} aria-label="Department">{["Engineering", "Science", "Commerce", "Arts", "Management"].map(o => <option key={o}>{o}</option>)}</select><select value={nw.qual} onChange={e => setNw({ ...nw, qual: e.target.value })} aria-label="Qualification">{["PhD", "Masters", "M.Phil"].map(o => <option key={o}>{o}</option>)}</select><Btn kind="pri" disabled={!nw.name.trim()} onClick={async () => { if (await c.post({ action: "save", kind: "faculty", data: nw }, "Faculty added")) setNw({ ...nw, name: "" }); }}>Add</Btn></div>}
      </Card>
      <div className="hx-col"><Card title="Department distribution">{fac.length ? <div className="hx-row center"><Donut parts={Object.entries(depts).map(([l, v], i) => ({ label: l, value: v, color: PAL[i % PAL.length] }))} label={fac.length} sub="faculty" /><Legend items={Object.keys(depts).map((n, i) => ({ name: n, color: PAL[i % PAL.length] }))} /></div> : <Empty>—</Empty>}</Card>
        <Card title="Qualification mix">{Object.entries(quals).map(([k, v]) => <div className="hx-li" key={k}><span className="hx-grow">{k}</span><div className="hx-bar" style={{ width: 100 }}><i style={{ width: `${v / fac.length * 100}%` }} /></div><b>{Math.round(v / fac.length * 100)}%</b></div>)}</Card>
        <Card title="Faculty lifecycle"><div className="hx-chain">{["Recruitment", "Onboarding", "Profile", "Teaching allocation", "Research", "Appraisal"].map(x => <span key={x}>{x}</span>)}</div></Card></div>
    </div>
  </>;
}
