"use client";
import { useEffect,useMemo,useState } from "react";
import { Activity,Bot,Cable,Clock3,Cloud,Database,FileClock,GitBranch,Headphones,KeyRound,Link2,ListFilter,LockKeyhole,Network,Phone,PhoneCall,Plus,RefreshCw,Route,Search,Settings2,ShieldCheck,TestTube2,Users,Video } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
type Data=Record<string,any>;
const tabs=[["overview","Overview",Activity],["inventory","Number Inventory",Database],["ranges","Extension Ranges",ListFilter],["virtual","Virtual IDs",Cloud],["cloud","Cloud Identities",Link2],["entry","External Entry Points",PhoneCall],["assignments","Assignments",Users],["routes","Routing Rules",Route],["rings","Ring Groups",Phone],["queues","Queues",Headphones],["ivr","IVR",GitBranch],["ai","AI Concierge",Bot],["meet","HavenMeet Bridges",Video],["providers","Providers",Cable],["porting","Porting and BYOC",Network],["testing","Call Testing",TestTube2],["analytics","Analytics",Activity],["audit","Audit History",FileClock],["settings","Settings",Settings2]];
const cls=(x:string)=>String(x||"").toLowerCase().replaceAll(" ","-");
async function api(path:string,method="GET",body?:Data){const r=await fetch(path,{method,headers:{"content-type":"application/json",...(method!=="GET"?{"idempotency-key":`xc_${crypto.randomUUID()}`}:{})},body:body?JSON.stringify(body):undefined}),d=await r.json();if(!r.ok)throw new Error(d.error||"XConnect request failed");return d;}
export function XConnectAdmin({notify,openMeeting}:{notify:(x:string)=>void;openMeeting:()=>void}){
 const [tab,setTab]=useState("overview"),[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[search,setSearch]=useState(""),[selected,setSelected]=useState("");
 const load=async()=>{try{setError("");setData(await api("/api/v1/xconnect"))}catch(e:any){setError(e.message)}};useEffect(()=>{load()},[]);
 const mutate=async(path:string,body:Data,message:string)=>{try{await api(path,"POST",body);notify(message);await load()}catch(e:any){notify(e.message)}};
 const identities=useMemo(()=>data?.identities?.filter((x:any)=>`${x.canonicalId} ${x.displayNumber} ${x.type} ${x.status}`.toLowerCase().includes(search.toLowerCase()))||[],[data,search]);
 if(error)return <div className="xc-auth"><LockKeyhole/><h3>Protected XConnect administration</h3><p>{error}</p><a href="/signin-with-chatgpt?return_to=%2F%3Fview%3Dcalls" target="_top">Sign in with an authorized Oak Haven account</a></div>;
 if(!data)return <div className="xc-auth"><RefreshCw/><p>Loading tenant-scoped communications data…</p></div>;
 let panel:any;
 if(tab==="overview")panel=<Overview data={data} openMeeting={openMeeting}/>;
 else if(["inventory","virtual","cloud"].includes(tab))panel=<Inventory items={identities.filter((x:any)=>tab==="virtual"?x.type==="virtual":tab==="cloud"?x.type==="cloud":true)} search={search} setSearch={setSearch} selected={selected} setSelected={setSelected} mutate={mutate}/>;
 else if(tab==="ranges")panel=<Cards title="Authorized tenant ranges" items={data.ranges.map((x:any)=>({title:`${x.rangeStart}–${x.rangeEnd}`,meta:x.numberType,detail:`Prefix ${x.prefix||"none"} · ${x.status}`}))} empty="No ranges configured."/>;
 else if(tab==="entry")panel=<EntryPoints data={data} mutate={mutate}/>;
 else if(tab==="assignments")panel=<Assignments data={data} selected={selected} setSelected={setSelected} mutate={mutate}/>;
 else if(tab==="routes")panel=<Routes data={data} selected={selected} setSelected={setSelected} notify={notify}/>;
 else if(tab==="providers")panel=<Cards title="Protected provider adapters" items={data.providers.map((x:any)=>({title:x.category,meta:x.provider||"No provider selected",detail:x.status}))} empty="No provider adapters."/>;
 else if(tab==="testing")panel=<Testing data={data} notify={notify}/>;
 else if(tab==="analytics")panel=<Analytics data={data}/>;
 else if(tab==="audit")panel=<Audit data={data}/>;
 else if(tab==="ai")panel=<Agent data={data} notify={notify}/>;
 else if(tab==="meet")panel=<Meet data={data} openMeeting={openMeeting}/>;
 else if(tab==="porting")panel=<Porting/>;
 else if(tab==="settings")panel=<Security/>;
 else panel=<OperationalLink kind={tab} data={data}/>;
 return <section className="xc-shell"><header className="xc-header"><div><span>XCONNECT CONTROL PLANE</span><h2>Tenant-safe identities and communications routing</h2><p>{data.viewer.tenant} · {data.viewer.role} · provider-neutral control</p></div><div><span className={`xc-sync ${cls(data.syncStatus)}`}>{data.syncStatus}</span><small>Updated {new Date(data.lastUpdated).toLocaleTimeString()}</small><Button variant="outline" onClick={load}><RefreshCw/>Refresh</Button></div></header><div className="xc-layout"><nav>{tabs.map(([id,label,Icon]:any)=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon/><span>{label}</span></button>)}</nav><main>{panel}</main></div></section>;
}
function Overview({data,openMeeting}:any){const verified=data.entryPoints.filter((x:any)=>x.provisioningStatus==="Connected"&&x.verificationStatus==="Verified").length;return <div className="xc-stack"><div className="xc-kpis">{[["Identities",data.identities.length],["Active",data.identities.filter((x:any)=>x.status==="active").length],["Verified entry points",verified],["Assignments",data.assignments.filter((x:any)=>x.status==="active").length],["Routes",data.routes.length],["Audit events",data.auditEvents.length]].map(([l,v])=><article key={l}><small>{l}</small><b>{v}</b><span>Authoritative records</span></article>)}</div><section className="xc-map"><header><div><span>RESOLUTION PIPELINE</span><h3>Stable identity, verified destination</h3></div><ShieldCheck/></header><div>{["Authenticated tenant","XConnect identity","Active rule","Verified mapping","Provider adapter","Staff, queue, AI, or HavenMeet"].map((x,i)=><article key={x}><i>{i+1}</i><b>{x}</b></article>)}</div></section><div className="xc-two"><article><h3>Internal namespace</h3><p>Extensions and <code>hcx:oak-haven:…</code> IDs remain internal. They are never presented as public telephone numbers.</p></article><article><h3>HavenMeet bridge</h3><p>Bridge 9100 may remain stable, but external dial-in requires a verified PSTN or SIP entry point.</p><Button onClick={openMeeting}>Open HavenMeet</Button></article></div></div>}
function Inventory({items,search,setSearch,selected,setSelected,mutate}:any){const [form,setForm]=useState({type:"extension",desired_number:""});const allocate=(reserve=false)=>mutate(`/api/v1/xconnect/identities/${reserve?"reserve":"allocate"}`,{type:form.type,desired_number:form.desired_number||undefined},`${reserve?"Reserved":"Allocated"} XConnect identity`);const action=(name:string)=>selected&&mutate(`/api/v1/xconnect/identities/${name}`,{identity_id:selected,reason:name==="release"?(prompt("Release reason")||""):undefined},`Identity ${name} completed`);return <div className="xc-stack"><div className="xc-toolbar"><label><Search/><Input value={search} onChange={(e:any)=>setSearch(e.target.value)} placeholder="Search identity, type, or status"/></label><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{["extension","department","queue","virtual","cloud","IVR","AI","meeting_bridge"].map(x=><option key={x}>{x}</option>)}</select><Input value={form.desired_number} onChange={e=>setForm({...form,desired_number:e.target.value.replace(/\D/g,"")})} placeholder="Optional requested identity"/><Button onClick={()=>allocate()}><Plus/>Allocate</Button><Button variant="outline" onClick={()=>allocate(true)}>Reserve</Button></div><div className="xc-table"><div className="head"><span>Identity</span><span>Canonical ID</span><span>Type</span><span>Status</span><span>Modified</span></div>{items.map((x:any)=><button key={x.id} className={selected===x.id?"selected":""} onClick={()=>setSelected(x.id)}><b>{x.displayNumber}</b><code>{x.canonicalId}</code><span>{x.type}</span><em className={cls(x.status)}>{x.status}</em><span>{new Date(x.updatedAt).toLocaleDateString()}</span></button>)}{!items.length&&<p className="xc-empty">No matching authoritative identities.</p>}</div><footer className="xc-actions"><Button disabled={!selected} variant="outline" onClick={()=>action("activate")}>Activate</Button><Button disabled={!selected} variant="outline" onClick={()=>action("suspend")}>Suspend</Button><Button disabled={!selected} variant="outline" onClick={()=>action("release")}>Release to quarantine</Button></footer></div>}
function EntryPoints({data,mutate}:any){const [f,setF]=useState({provider_id:"",provider_resource_id:"",entry_point_type:"pstn",address:"",country_code:"NG",capabilities:["voice"]});return <div className="xc-stack"><div className="xc-form"><h3>Register a real provider resource</h3><Input placeholder="Provider name" value={f.provider_id} onChange={e=>setF({...f,provider_id:e.target.value})}/><Input placeholder="Provider resource ID" value={f.provider_resource_id} onChange={e=>setF({...f,provider_resource_id:e.target.value})}/><select value={f.entry_point_type} onChange={e=>setF({...f,entry_point_type:e.target.value})}>{["pstn","sip_uri","sip_trunk","whatsapp_business","carrier_resource","BYOC"].map(x=><option key={x}>{x}</option>)}</select><Input placeholder="Verified number or SIP address" value={f.address} onChange={e=>setF({...f,address:e.target.value})}/><Button onClick={()=>mutate("/api/v1/xconnect/entry-points/register",f,"Entry point registered as Awaiting Verification")}>Register</Button><p>Registration never activates a resource. A provider test ID is required before Connected status.</p></div><Cards title="External entry points" items={data.entryPoints.map((x:any)=>({title:x.address,meta:`${x.providerId} · ${x.entryPointType}`,detail:`${x.verificationStatus} · ${x.provisioningStatus}`}))} empty="No real external entry points are registered."/></div>}
function Assignments({data,selected,setSelected,mutate}:any){const [target,setTarget]=useState({target_type:"user",target_id:""});return <div className="xc-stack"><div className="xc-toolbar"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select identity</option>{data.identities.map((x:any)=><option key={x.id} value={x.id}>{x.displayNumber} · {x.type}</option>)}</select><select value={target.target_type} onChange={e=>setTarget({...target,target_type:e.target.value})}>{["user","department","queue","ring_group","IVR","AI_agent","meeting_room","voicemail"].map(x=><option key={x}>{x}</option>)}</select><Input placeholder="Authorized target ID" value={target.target_id} onChange={e=>setTarget({...target,target_id:e.target.value})}/><Button onClick={()=>mutate("/api/v1/xconnect/identities/assign",{identity_id:selected,...target},"Identity assigned")}>Assign</Button><Button variant="outline" onClick={()=>mutate("/api/v1/xconnect/identities/unassign",{identity_id:selected},"Identity unassigned")}>Unassign</Button></div><Cards title="Assignment history" items={data.assignments.map((x:any)=>({title:`${x.targetType}: ${x.targetId}`,meta:data.identities.find((i:any)=>i.id===x.communicationIdentityId)?.displayNumber||"Identity",detail:x.status}))} empty="No assignments."/></div>}
function Routes({data,selected,setSelected,notify}:any){const [result,setResult]=useState<any>(null);const test=async()=>{const item=data.identities.find((x:any)=>x.id===selected);if(!item)return notify("Select an identity");try{setResult(await api(`/api/v1/xconnect/routes/resolve?identity=${encodeURIComponent(item.canonicalId)}`));notify("Route resolved from tenant-scoped records")}catch(e:any){setResult({error:e.message});notify(e.message)}};return <div className="xc-stack"><div className="xc-toolbar"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select identity</option>{data.identities.map((x:any)=><option key={x.id} value={x.id}>{x.displayNumber} · {x.type}</option>)}</select><Button onClick={test}>Test route</Button></div>{result&&<pre className="xc-result">{JSON.stringify(result,null,2)}</pre>}<Cards title="Active routing records" items={data.routes.map((x:any)=>({title:`${x.destinationType}: ${x.destinationId}`,meta:`Priority ${x.priority}`,detail:x.status}))} empty="No active routing rules. Route tests return no destination."/></div>}
function Testing({data,notify}:any){return <div className="xc-stack"><h3>End-to-end call test gate</h3><p>Tests become available only after a real entry point is verified and Connected. No simulated call changes status.</p>{data.entryPoints.map((x:any)=><article className="xc-check" key={x.id}><span><b>{x.address}</b><small>{x.providerId} · {x.verificationStatus}</small></span><Button disabled={x.verificationStatus!=="Verified"} onClick={()=>notify("Live test runner requires the configured provider adapter")}>Run live test</Button></article>)}{!data.entryPoints.length&&<div className="xc-empty">Register and verify a real provider entry point first.</div>}</div>}
function Analytics({data}:any){const status=data.identities.reduce((a:any,x:any)=>(a[x.status]=(a[x.status]||0)+1,a),{});return <div className="xc-kpis">{Object.entries(status).map(([k,v]:any)=><article key={k}><small>{k}</small><b>{v}</b><span>Database records</span></article>)}{!Object.keys(status).length&&<p className="xc-empty">No identity activity yet.</p>}</div>}
function Audit({data}:any){return <div className="xc-table"><div className="head"><span>Action</span><span>Actor</span><span>Correlation</span><span>Identity</span><span>Time</span></div>{data.auditEvents.map((x:any)=><div key={x.id}><b>{x.action}</b><span>{x.actorId.slice(0,12)}…</span><code>{x.correlationId}</code><span>{x.identityId||"Entry point"}</span><time>{new Date(x.createdAt).toLocaleString()}</time></div>)}</div>}
function Agent({data,notify}:any){const p=data.providers.find((x:any)=>x.category==="OpenAI Realtime API");return <div className="xc-agent"><Bot/><div><span className={`xc-status ${cls(p.status)}`}>{p.status}</span><h3>Amara · Official Oak Haven Voice</h3><p>Voice profiles remain inactive until OpenAI Realtime API credentials, authorized voice assets, verified Oak Haven knowledge, secure tools, and a real handoff test succeed.</p><ul><li>Always identifies itself as AI</li><li>Stops or hands off when requested</li><li>Never invents room availability or prices</li><li>Never collects raw payment-card data</li><li>Requires staff approval for refunds, cancellations, overrides, contracts, and security actions</li></ul><Button disabled={p.status!=="Connected"} onClick={()=>notify("No live AI session was created")}>Start verified test</Button></div></div>}
function Meet({data,openMeeting}:any){const bridges=data.identities.filter((x:any)=>x.type==="meeting_bridge");return <div className="xc-stack"><Cards title="HavenMeet bridge identities" items={bridges.map((x:any)=>({title:x.displayNumber,meta:x.canonicalId,detail:x.status}))} empty="No HavenMeet bridge identity is allocated."/><p>External dial-in requires a verified PSTN/SIP mapping and private meeting-code validation.</p><Button onClick={openMeeting}>Open native HavenMeet</Button></div>}
function Porting(){return <div className="xc-stack"><h3>Nigerian number, porting, SIP trunk, and BYOC readiness</h3>{["Number ownership evidence","Carrier availability or porting approval","Inbound and outbound calling","Verified caller ID","Emergency-service limitations","International dialing policy","Failover and traditional-number backup","WhatsApp number eligibility"].map(x=><article className="xc-check" key={x}><Clock3/><span><b>{x}</b><small>Awaiting qualified carrier confirmation</small></span></article>)}</div>}
function Security(){return <div className="xc-two"><article><ShieldCheck/><h3>Isolation and authorization</h3><p>Tenant context is server-derived. Every mutation is tenant-scoped and restricted to the protected administrator allowlist.</p></article><article><KeyRound/><h3>Secrets and fraud controls</h3><p>Provider secrets stay server-side. Idempotency, rate limits, destination restrictions, audit history, and quarantine reduce duplicate allocation and fraud risk.</p></article></div>}
function OperationalLink({kind,data}:any){const copy:any={rings:["Ring Groups","Configure ring-all, sequential, round-robin, longest-idle, skills, priority, language, and overflow groups in Voice Operations."],queues:["Queues","Live queue records and verified metrics are managed in Voice Operations."],ivr:["IVR","Versioned greetings, business-hours routes, approval, testing, and rollback are managed in Voice Operations."]};const [title,text]=copy[kind];return <div className="xc-stack"><h3>{title}</h3><p>{text}</p><article className="xc-check"><ShieldCheck/><span><b>Integrated with HavenConnect Voice Operations</b><small>{data.syncStatus} · updated {new Date(data.lastUpdated).toLocaleTimeString()}</small></span></article></div>}
function Cards({title,items,empty}:{title:string;items:any[];empty:string}){return <section className="xc-cards"><h3>{title}</h3>{items.map((x,i)=><article key={`${x.title}-${i}`}><b>{x.title}</b><span>{x.meta}</span><em className={cls(x.detail)}>{x.detail}</em></article>)}{!items.length&&<p className="xc-empty">{empty}</p>}</section>}
