"""Shared, reviewable topic library. Rules simulations are not live AI labs."""
RAW = '''
scope|Define the decision boundary|An assistant can suggest an action without permission to perform it. Name the decision owner, allowed inputs, prohibited outputs and measurable baseline before selecting a model.|Draw an input-to-review map with two mandatory human checkpoints.|Which boundary is testable?|A named task with allowed actions and a human escalation owner|A promise to automate the department|routing
data|Inspect data quality|Missing values and duplicates change metric denominators. Separate schema checks from business rules; reject malformed records visibly rather than silently converting them to ordinary inputs.|Count invalid and missing values before selecting records for analysis.|How should missing confidence be handled?|Flag it and send the record for review|Silently replace it with perfect confidence|quality
baseline|Build a measurable baseline|Keep baseline and candidate evaluations on the same held-out examples. Define the cost of false acceptance and unnecessary review. A simple rule is a useful reference, even when a later model is more complex.|Compare review rates at two thresholds on the same records.|What makes a comparison fair?|The same examples and metric definitions|Replacing difficult examples after seeing results|routing
prompt|Write bounded instructions|Specify the task, allowed evidence, output fields and escalation condition. Examples demonstrate format; they do not grant new permissions. Missing support should lead to an unresolved result.|Write an instruction card with sources, schema, boundaries and two examples.|What belongs in an instruction card?|An explicit missing-evidence rule|An instruction to always sound certain|retrieval
schema|Validate structured outputs|Parseable output is not automatically correct. Check required fields, types, ranges and allowed categories. Generated identifiers and tool arguments remain untrusted until independently validated.|Define three result fields and reject an out-of-range score.|What does JSON validity alone establish?|Syntactic validity only|That the content is factually correct|quality
retrieval|Retrieve evidence before drafting|Retrieval narrows available evidence. Lexical matching is a transparent baseline but misses paraphrases. Similarity does not establish support; inspect source identifiers and unanswered cases.|Rank source snippets by token overlap and identify an unsupported query.|When should a grounded answer abstain?|When sources do not support the claim|When the source title is short|retrieval
chunks|Preserve evidence boundaries|Chunking trades context against noise. Splitting conditions from exceptions can change meaning. Overlap preserves continuity but duplicates evidence and increases retrieval volume.|Compare whole-document and sentence-level retrieval on a policy exception.|What is a chunking risk?|Separating an exception from its condition|Making all source facts invalid|retrieval
evaluation|Create an evaluation set|Include ordinary, ambiguous, abstention and adversarial cases. Label expected outcomes before running the candidate. Aggregate accuracy can hide severe failures.|Write six expected outcomes, including two cases that must not trigger action.|When should expected labels be assigned?|Before viewing candidate outputs|After seeing which labels maximize the score|evaluation
tools|Constrain tool permissions|Tools create consequences beyond text. Use allowlists, validate arguments, separate reads from writes and require approval for consequential operations. Never present a tool error as success.|Define read-only lookup and approval-gated update contracts.|What prevents an unauthorized write?|An independent permission check at execution time|A friendly warning alone|routing
state|Model workflow state|Explicit states make retries and handoffs inspectable. Define legal transitions and terminal states. A retry must detect completed work rather than duplicate an action.|Draw intake, validation, review, approval and closed states.|How should a retry handle a completed action?|Detect the prior result and avoid repeating it|Perform it twice to be certain|workflow
memory|Separate memory by purpose|Temporary context, approved knowledge and audit records have different access and retention needs. Storing everything increases exposure and retains stale conclusions. Define correction and deletion paths.|Classify five fields into context, knowledge or aggregate audit data.|What fits an aggregate audit log?|An outcome count without message text|All private conversations indefinitely|quality
orchestration|Assign bounded agent roles|Multiple agents still require an accountable workflow. Define narrow input/output contracts, shared state and a stopping rule. Escalate unresolved conflicts instead of creating endless debate.|Specify researcher, checker and coordinator roles.|Who resolves conflicting outputs?|A defined coordinator rule or human owner|The agent that writes most|workflow
protocol|Define tool contracts|Interoperability requires stable names, arguments, results and errors. A protocol transports requests but does not make content trustworthy. Version the contract and test invalid inputs.|Write mock request, result and permission-error examples.|Does compatibility establish authorization?|No; permissions need separate enforcement|Yes; compatible tools can access everything|quality
security|Test hostile instructions|Retrieved documents and tool results are data, not authority to change policy. Keep permissions outside content. Test attempts to expand access or extract restricted fields.|Add a hostile snippet and show why it cannot expand the allowlist.|How should source instructions to reveal secrets be treated?|As untrusted content|As a higher-priority system rule|routing
privacy|Minimize data exposure|Collect only fields needed for the stated task. Separate identifiers and define retention. Removing names does not guarantee anonymity because other fields may be linked.|Remove unnecessary fields and describe remaining linkage risks.|Does removing names guarantee anonymity?|No; combinations of fields may identify people|Yes; names are the only identifier|quality
fairness|Compare error burdens|Overall scores can hide different error or review rates. Use fictional queues here, not real protected traits. Small synthetic samples suggest questions, not causal conclusions.|Calculate queue-level review rates and state sampling limitations.|What follows from unequal synthetic rates?|Investigate definitions and sampling first|Immediately conclude unlawful discrimination|evaluation
tracing|Record useful traces|Connect requests to steps, versions, tool outcomes and human decisions without retaining unnecessary sensitive text. Distinguish attempted actions from completed actions.|Design a five-field trace and locate a failed transition.|Which field distinguishes retries?|A stable operation identifier and attempt status|A decorative display label|workflow
release|Release with rollback|Identify the configuration, evidence, owner and rollback trigger. Restoration needs a known previous state. A deployment announcement is not proof of successful operation.|Write a release checklist with a failed-evaluation rollback trigger.|What makes rollback meaningful?|A tested restoration procedure and known prior version|A promise to fix problems later|workflow
cost|Measure total workflow cost|Include review time, retries, maintenance and setup as well as generation. Estimate ranges. Time saved does not automatically equal cash saved.|Calculate net minutes saved at two thresholds and identify omitted costs.|Why can fewer model calls still cost more?|More human review and recovery effort|Model calls are always free|cost
ml|Separate training and evaluation|Tuning on held-out labels creates optimistic estimates. Preserve a final test set and compare with a simple baseline. This offline exercise evaluates a rule, not a trained ML model.|Split records into development and test sets and evaluate a fixed rule.|What causes evaluation leakage?|Repeated tuning on held-out labels|Keeping test examples unseen during tuning|evaluation
neural|Explain representation limits|Representations encode learned patterns, not guaranteed truth. Similarity is task-dependent and can fail under distribution shift. A deterministic simulation is not neural training.|Diagram inputs, representation, prediction and validation; identify a shift.|What does high similarity establish?|Similarity under that representation, not truth|That the answer is authoritative|retrieval
forecast|Review predictive actions|A score is uncertain and must be interpreted against action costs. Separate false positives from false negatives. A configured threshold stands in for model output in this simulation.|Compare two review thresholds and add mandatory approval.|What precedes a consequential action?|The approved review and authorization process|Act automatically on above-average scores|routing
workflow|Build a visual approval flow|No-code systems still need input contracts, error paths and owners. Connect validation, branching, review and recording. Test negative paths as well as success paths.|Configure the supplied simulator and export its decision table.|What should happen when a required field is absent?|An explicit needs-data branch|Default success|workflow
productivity|Measure changes in work|Compare comparable tasks and include setup and checking time. Track quality with speed so faster errors do not look like improvement.|Compare baseline and assisted time including review.|Which measure is fair?|Baseline minus assisted time including review|Baseline minus generation time alone|cost
process|Map operational bottlenecks|Map queues, decisions and rework rather than ideal steps only. Improving a fast step may not improve the bottleneck. Measure cycle time before choosing an intervention.|Map an intake queue and select one measurable intervention.|What is a bottleneck?|The constrained step limiting throughput|Always the newest technology|workflow
strategy|Prioritize an AI portfolio|Compare value, readiness and risk. High projected return does not replace usable data and controls. Stage investment around evidence gates.|Score three fictional use cases and defend one deferral.|What if a valuable case lacks usable data?|Resolve readiness before full deployment|Assume quality improves after launch|cost
governance|Assign decision rights|Name approvers, operators and stop-authority owners. Connect each risk to a control, evidence and review interval. A policy without an operational checkpoint does not enforce itself.|Create three risk entries with owner, control and evidence.|What makes a register actionable?|Named owners and testable controls|A risk list without decisions|workflow
change|Plan adoption and feedback|Adoption includes redesign, training and escalation, not tool access alone. Usage metrics do not establish quality or business value.|Design a pilot with feedback and a stop condition.|What does high usage alone show?|Activity, not effectiveness|That the system is safe|cost
coding|Review generated code|Generated code needs independent correctness and security checks. Test behavior and edge cases rather than copying the implementation. Keep secrets out of prompts.|Write normal, boundary and malformed-input tests.|Which test is stronger?|An independently specified boundary result|Repeating the implementation calculation|quality
ci|Design independent quality gates|Fail visibly when required checks fail. Separate code authoring, review and deployment authorization. Do not let an automated reviewer approve its own unverified output.|Design merge and deployment gates with rollback evidence.|May a coding agent approve its own deployment?|Not without independent gates and authorization|Yes because it understands its output|workflow
finance|Reconcile synthetic records|Compare amounts against a defined tolerance and send exceptions to reviewers. A matching amount is not proof of legitimacy; a mismatch is not proof of fraud. No investment or lending advice is produced.|Flag mismatches and draft a reason-coded review memo.|What does an exception mean?|It needs investigation|It proves fraud|reconcile
health|Support non-clinical operations|Administrative scheduling and documentation can use bounded support, but ambiguous information must route to trained people. Never use real patient data or recommend diagnosis or treatment here.|Route fictional administrative cases and minimize the audit trail.|Which task fits this course?|Synthetic scheduling support|Selecting treatment|routing
capstone|Defend an evidence-based handover|Connect claims to reproducible evidence and explain failures. Present baseline, design, controls and rollback. A polished success-only demonstration is not enough.|Reproduce one success and one failure; defend the boundary.|What is strongest evidence?|Reproducible tests and candid failure analysis|A success-only recording|evaluation
'''
TOPICS={}
for row in RAW.strip().splitlines():
    key,title,lesson,task,q,correct,wrong,family=row.split('|')
    TOPICS[key]=dict(key=key,title=title,lesson=lesson,task=task,question=q,correct=correct,wrong=wrong,family=family)
SEQUENCES={
1:'scope tools state memory orchestration protocol evaluation security tracing governance retrieval chunks schema fairness cost release coding ci privacy capstone',
2:'scope data baseline prompt schema retrieval chunks evaluation tools state memory workflow security privacy fairness tracing cost release governance capstone',
3:'scope data baseline ml evaluation fairness neural forecast privacy prompt schema retrieval chunks tools state orchestration security tracing governance capstone',
4:'scope coding prompt schema data ci security tools workflow tracing release capstone capstone capstone',
5:'scope data forecast ml evaluation fairness workflow privacy governance capstone capstone capstone capstone capstone',
6:'scope prompt retrieval chunks schema workflow security evaluation governance capstone capstone capstone',
7:'scope prompt productivity workflow privacy capstone',
8:'scope process data workflow tools cost governance change evaluation capstone capstone capstone',
9:'scope strategy cost governance privacy fairness change process evaluation capstone capstone capstone',
10:'scope finance data baseline finance tools evaluation privacy governance capstone',
11:'scope health data process health privacy evaluation fairness governance capstone'}
CONTEXTS={1:('a multi-agent service desk','agent systems engineering','Python functions, JSON and HTTP concepts'),2:('an internal knowledge desk','retrieval-assistant development','Python functions and data structures'),3:('an operations analysis team','applied AI analysis','Python basics and introductory algebra'),4:('a software delivery team','software quality automation','Python, Git concepts and automated testing'),5:('a predictive service queue','visual predictive workflows','Spreadsheet familiarity; no coding required'),6:('a departmental request desk','no-code knowledge workflows','Basic digital literacy; no coding required'),7:('a personal task workspace','productivity workflow design','Basic digital literacy; no coding required'),8:('a procurement intake process','operations improvement','Experience describing a business process'),9:('an AI investment committee','AI adoption planning','Planning or leadership experience'),10:('a synthetic reconciliation desk','finance operations support','Spreadsheet analysis; Python optional'),11:('a synthetic scheduling office','non-clinical operations support','Administrative workflow familiarity; Python optional')}
