"""Additional program designs. Draft educational content, not publication approval."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
TOPICS={
1:[['Bound autonomy before building','Measure model cost and context','Specify instruction and output contracts','Make tools retry-safe','Retrieve from a traceable corpus','Route questions to supporting evidence','Compare bounded planning loops','Budget and expire agent memory','Reconcile two synthetic evidence sources','Defend the foundation build'],['Route between small and hosted models','Coordinate workers and reviewers','Compare explicit orchestration patterns','Constrain protocol tools and identities','Review agent-assisted repository changes','Calibrate evaluation against human judgments','Trace failures and hostile inputs','Rehearse deploy and rollback','Audit a synthetic lending recommendation','Defend the multi-agent evidence package']],
12:[['Frame a problem worth solving','Choose a learning method for a product need','Compare neural architectures and data demands','Specify consent and provenance for generated media','Prototype a grounded information assistant','Choose an agent interaction pattern','Storyboard control and error recovery','Design a human and machine operating model','Test economics and societal risk assumptions','Pitch a responsible product proposal']],
13:[['Set a leadership learning agenda','Challenge claims about generative systems','Build a privacy-aware prompt playbook','Map opportunities across business functions','Draft accountable AI-use rules','Assess readiness and workforce support','Compare augmentation and task redesign','Prioritize opportunities with evidence','Assign owners and measurable milestones','Defend an organizational AI strategy'],['Estimate agent value and total cost','Compare platforms through a sandbox prototype','Map enterprise interfaces and approvals','Prepare an agent incident response exercise','Select business-function agent patterns','Specify a measurable pilot','Test safety and operational boundaries','Design an accountable governance review','Plan adoption and evaluate value','Defend responsible agent adoption']],
14:[['Choose a bounded applied-agent problem','Model autonomy and stopping conditions','Build a structured generation baseline','Compare plans against observable evidence','Coordinate specialist workers','Connect a recoverable workflow','Review a synthetic report with citations','Expose a scoped database tool','Test tool-protocol denial cases','Defend an integrated midterm prototype'],['Route retrieval across data sources','Measure grounding and trace quality','Estimate product value under uncertainty','Design transparent approval interfaces','Build a test-first delivery pipeline','Compare deployment options and costs','Rehearse a cloud deployment design','Assemble a traceable project portfolio','Validate product and governance assumptions','Present the prototype and strategy defense']]}
TITLES={1:'Professional Certificate in Agentic AI Systems',12:'Certificate in Designing & Building AI Products and Services',13:'Applied AI Leadership Bundle: Generative and Agentic AI for Organizational Transformation',14:'Certificate in Applied Agentic AI: Systems, Design & Impact'}
COMP={1:['Justify bounded agent autonomy against a non-agent baseline.','Implement grounded retrieval and retry-safe tool contracts.','Compare planning, memory and multi-agent designs using test evidence.','Evaluate reliability, bias, permissions and human-review controls.','Defend a monitored system and a recoverable deployment plan.'],12:['Match learning methods and neural architectures to a justified product problem.','Validate data, cost and technical assumptions in a product design.','Assess retrieval and tool-using agents for fit and failure risk.','Design accessible human oversight and error recovery.','Pitch an evidence-based business case and implementation roadmap.'],13:['Prioritize organizational opportunities using value, effort and risk evidence.','Design privacy-aware generative workflows and responsible AI-use rules.','Evaluate agent platforms, integrations and operating costs.','Specify governance, incident response and measurable pilot controls.','Defend an adoption roadmap with owners, metrics and human accountability.'],14:['Build a bounded multi-agent prototype from explicit requirements.','Integrate retrieval and scoped protocol tools using synthetic data.','Evaluate grounding, trace quality and operational failures.','Design transparent agent interfaces and a reproducible delivery process.','Defend a portfolio and product strategy with measured limitations.']}
PROJECTS={1:['Two-source evidence reconciliation','Source-quality research brief','Synthetic credit-review recommendation dossier'],12:['Grounded assistant concept','Human oversight storyboard','Opportunity evidence map','Product brief and stakeholder pitch'],13:['Private prompt playbook','Organizational opportunity portfolio','AI strategy presentation','Agent adoption and governance plan'],14:['Synthetic report consistency reviewer','Evidence-routing assistant','Document retrieval workbench','Notes-to-actions approval workflow','Scoped data and ticket tool','Support-routing team simulation','Agent trace comparison dashboard','Product strategy and working prototype defense']}
def designs():
 result=[]
 for n,blocks in TOPICS.items():
  courses=[]
  for b,topics in enumerate(blocks,1):
   modules=[]
   for w,t in enumerate(topics,1):
    modules.append({'week':w,'title':t,'status':'draft activity brief; full materials pending','outcomes':[{'id':f'P{n}-B{b}-W{w}-O1','competency':f'C{(w-1)%5+1}','text':f'Produce and explain an evidence artifact for: {t.lower()}.'},{'id':f'P{n}-B{b}-W{w}-O2','competency':'C4','text':'Test a failure assumption and identify the accountable human decision.'}],'activity':{'student':f'Using a fictional Academy service, {t.lower()}. Submit the artifact, assumptions, one failure example and a short limitations note. Do not use personal or customer records.','instructor':'Compare the artifact with its stated requirements; inspect evidence and failure handling, then provide feedback without replacing the learner work. Detailed solution pending.'}})
   courses.append({'id':f'P{n:02d}-B{b}','title':('Agent foundations' if b==1 else 'Production multi-agent systems') if n==1 else ('Generative AI leadership' if b==1 else 'Agentic AI leadership') if n==13 else ('Applied agent foundations' if b==1 else 'Applied agent delivery') if n==14 else 'AI product design','weeks':10,'sequence':b,'modules':modules,'finalAssessment':'Capstone defense' if b==len(blocks) else 'Midterm project and foundation exam' if n==1 else 'Course project defense'})
  result.append({'program':n,'title':TITLES[n],'brand':'Scholarion Academy','faculty':'Dr. Martins Donbruce Idahosa','facultyBio':None,'state':'draft','weeks':10,'totalWeeks':10*len(blocks),'courses':courses,'modules':courses[0]['modules'],'sessions':[],'competencies':[{'id':f'C{i}','text':s} for i,s in enumerate(COMP[n],1)],'projects':[{'title':t,'status':'design brief','data':'Synthetic or licensed data only; a reviewed data card is required.'} for t in PROJECTS[n]],'capstone':PROJECTS[n][-1]+('. Educational simulation only: synthetic applicant audit, protected-attribute bias tests, reason-code review and an explicit human-underwriter decision. Never make a final credit decision.' if n==1 else '.'),'rubric':[{'criterion':c,'points':v} for c,v in [('Problem and assumptions',15),('Artifact and reproducibility',25),('Evaluation evidence',25),('Human oversight and risk',25),('Defense and communication',10)]],'audience':'Python-capable builders' if n in (1,14) else 'Product managers and innovation leads' if n==12 else 'Organizational leaders and managers','prerequisites':'Programming fundamentals required; work experience preferred, not mandatory.' if n==14 else 'Python required.' if n==1 else 'No coding background required.','weeklyHours':[8,10] if n==1 else [6,6] if n==12 else [8,8] if n==14 else None,'learningHours':[160,200] if n==1 else [60,60] if n==12 else [160,160] if n==14 else None,'commercial':{'fee':None,'currency':None,'startDate':None,'deadline':None,'timezone':None,'installments':None,'refundPolicy':None,'advisorEmail':None,'advisorPhone':None,'mode':'sandbox','applicationsEnabled':False},'credential':{'title':'Scholarion Academy Certificate of Completion','badge':TITLES[n],'issuanceEnabled':False,'ceu':False,'perCourse':n==13,'bundleBadge':n==13},'dependencyNotes':'Retain #9; proposed mapping from #13 course 2 requires academic approval. No automatic credit and no retirement.' if n==13 else 'Transfer and non-duplication mappings remain proposed; no automatic credit.','notes':'','publicationAllowed':False,'gaps':['Complete original lessons, slide scripts and licensed readings','Executable starter and instructor notebooks with synthetic data cards','Validated quizzes, assignments and scoring policies','Confirmed tool versions and educational licenses','Faculty biography, delivery schedule and support capacity','Approved finance, completion and academic publication configuration']})
 return result

def build():
 items=designs();(ROOT/'dist/data/additional-programs.json').write_text(json.dumps(items,indent=2),encoding='utf-8')
 path=ROOT/'dist/data/programs.json';catalog=json.loads(path.read_text(encoding='utf-8'))
 for p in items:
  old=next((x for x in catalog if x['id']==p['program']),None)
  if old is None:old={'id':p['program']};catalog.append(old)
  old.update(title=p['title'],length=f"{p['totalWeeks']} weeks ({len(p['courses'])} ten-week course blocks)",format='Online; live schedule pending',structure=[c['title']+' — 10 weeks' for c in p['courses']],weeks=[[f"B{c['sequence']} W{m['week']}",m['title']] for c in p['courses'] for m in c['modules']],summary=p['competencies'][0]['text'],capstone=p['capstone'],track='Builder' if p['program'] in (1,14) else 'Business & Leadership',coding=p['prerequisites'],status='Draft curriculum',type='Certificate program',level='Advanced' if p['program'] in (1,14) else 'Intermediate',commercial=p['commercial'],credential=p['credential']['title'])
 catalog.sort(key=lambda x:x['id']);path.write_text(json.dumps(catalog,ensure_ascii=False),encoding='utf-8');(ROOT/'dist/catalog-data.js').write_text('const programCatalog = '+json.dumps(catalog,ensure_ascii=False)+';\n',encoding='utf-8')
if __name__=='__main__':build()
