"""Faculty-review package; product-owner approval is not faculty publication approval."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
RAW='''Build a repeatable agent workspace|C1|commons-01|Separate configuration, secrets and request execution.|Build a synthetic request client with timeout, bounded concurrency and environment-based configuration.|Show that missing secrets fail safely and cancelled requests terminate.
Deliver a typed service boundary|C1|commons-07|Validate requests and isolate presentation from domain actions.|Expose a synthetic triage function through a typed interface; add streaming event records.|Reject malformed input and prove an interrupted stream cannot duplicate an action.
Control context and structured responses|C1|commons-06|Compare prompt variants using a fixed test set and token budget.|Design a response schema for fictional policy questions and evaluate two instruction variants.|Report schema failures and abstentions without claiming a model run that did not occur.
Measure retrieval before generation|C2|commons-08|Evaluate lexical and semantic retrieval independently of answer style.|Chunk a synthetic catalog, define relevance labels and compare retrieval candidates.|Calculate recall at k from the labeled set and explain a missed relevant record.
Build an evidence-first answer chain|C2|commons-09|Preserve provenance through loading, retrieval and answer assembly.|Implement a handbook pipeline that returns source identifiers and refuses unsupported answers.|Trace each factual statement to a source and test an empty retrieval result.
Constrain the tool-using loop|C3|commons-10|Bound tool permissions, retries and execution steps.|Create a read-only synthetic inventory agent with typed tool inputs and an action budget.|Reject an unauthorized write and stop a repeated tool failure within the budget.
Represent decisions as explicit state|C3|commons-11|Define graph transitions and terminal conditions before execution.|Build a branching research workflow with deterministic node tests.|Prove every branch terminates or reaches a bounded review state.
Resume safely after interruption|C3|commons-11|Persist checkpoints without bypassing human approval.|Add approval interrupts, restart recovery and idempotent side-effect simulation.|Restart between approval and completion; demonstrate exactly one committed action.
Make evaluation reproducible|C4|commons-15|Distinguish deterministic tests, human labels and model judgments.|Create held-out cases, trace identifiers and regression thresholds for the handbook assistant.|Show a deliberately degraded candidate fails the release threshold.
Design a least-privilege tool server|C3|commons-12|Separate protocol transport from tool authorization.|Specify a catalog lookup tool, resource identifiers, input constraints and permission scopes.|Demonstrate denied access and schema validation with a protocol-independent test harness.
Compose tools without expanding access|C3|commons-12|Propagate only the minimum permitted context between tools.|Connect two synthetic tool adapters through a bounded workflow; document trust boundaries.|An upstream request must not grant downstream privileges.
Use memory with evidence and expiry|C3|commons-11|Separate durable facts from uncertain working notes.|Implement a research notebook with source references, confidence and expiry fields.|Expired or unsupported memories cannot become verified claims.
Coordinate specialists with bounded delegation|C3|commons-13|Assign responsibilities and prevent circular delegation.|Build a fictional conference planner with explicit roles and a maximum delegation depth.|Inject a circular request and verify termination with a review record.
Evaluate multi-hop retrieval|C2|commons-14|Compare baseline retrieval with graph-assisted evidence traversal.|Create a small synthetic relationship graph and labeled multi-hop questions.|Report evidence coverage and a case where added graph complexity does not help.
Package a recoverable release|C4|commons-18|Separate build artifacts, configuration and runtime health.|Write container and deployment designs for the synthetic support platform, with rollback steps.|Demonstrate local startup/shutdown and specify which cloud checks remain unrun.
Connect operational signals to decisions|C4|commons-16|Measure latency, errors and cost with explicit denominators.|Instrument a test workload and propose an adaptation experiment using held-out evidence.|Explain why tuning should or should not proceed; simulated measurements are labeled.
Test the trust boundary|C5|commons-17|Treat retrieved instructions as untrusted content.|Create injection, disclosure and malformed-tool-input cases for the support platform.|Show denied actions, safe responses and redacted trace metadata.
Make automation retry-safe|C4|commons-19|Distinguish delivery retries from business action retries.|Build a synthetic webhook workflow with deduplication, failure routing and replay rules.|Replay the same event twice and prove only one business action is recorded.
Defend the capstone architecture|C5|commons-20|Explain scope, risks and evaluation before final implementation.|Submit a support-platform proposal, architecture, dataset card, test plan and peer review.|Resolve critical review findings or explicitly record a blocked release.
Demonstrate readiness and limitations|C5|commons-15|Support a final recommendation with reproducible evidence.|Present the capstone, run failure demonstrations, supply runbook and retrospective.|Mentor scores the rubric and records the live defense outcome.'''
competencies=[{'id':'C1','text':'Build typed, reproducible AI application boundaries.'},{'id':'C2','text':'Evaluate retrieval and answer provenance.'},{'id':'C3','text':'Orchestrate bounded agents and authorized tools.'},{'id':'C4','text':'Test, observe and deliver recoverable systems.'},{'id':'C5','text':'Defend responsible system design with evidence.'}]
sessions=[]
for i,row in enumerate(RAW.splitlines(),1):
 title,c,m,outcome,lab,check=row.split('|')
 sessions.append({'id':f'P15-S{i:02}','weekend':(i+1)//2,'day':'Saturday' if i%2 else 'Sunday','title':title,'competency':c,'commons':{'id':m,'version':'0.1.0-draft'},'liveMinutes':180,'outcome':outcome,'lab':lab,'checkpoint':check,'agenda':[{'minutes':20,'activity':'Concept and worked demonstration'},{'minutes':70,'activity':'Guided build'},{'minutes':10,'activity':'Break'},{'minutes':56,'activity':'Independent failure testing and peer review'},{'minutes':24,'activity':'Checkpoint and reflection'}],'submission':['Implementation or design artifact','Test evidence with environment details','Limitations and remediation notes'],'makeup':'Review the approved recording and submit the session lab. Faculty validates equivalent participation.','passRule':'Faculty records passed only when the session-specific checkpoint is demonstrated; no automatic grade.'})
projects=[('P1','Request routing with a review boundary',[1,2,3]),('P2','Fictional policy decision comparison',[3]),('P3','Catalog evidence finder',[4]),('P4','Source-linked handbook assistant',[5]),('P5','Recoverable research workflow',[7,8]),('P6','Bounded conference coordination',[12,13]),('P7','Reviewed content production',[13]),('P8','Research memory with uncertainty',[12,14]),('P9','Replay-safe order workflow',[18]),('P10','Support operations capstone',[19,20])]
rubric=[{'criterion':'Scope and architecture','points':15},{'criterion':'Retrieval and source quality','points':15},{'criterion':'Authorized tools and orchestration','points':20},{'criterion':'Evaluation and failure recovery','points':20},{'criterion':'Security and governance','points':15},{'criterion':'Delivery, documentation and defense','points':15}]
package={'id':15,'version':'0.1.0','brand':'Scholarion Academy','title':'Advanced Certificate in Agentic AI Engineering — Weekend Intensive','state':'faculty_review_required','productOwnerDecision':'Retain all programs; build #15 first. Approved by user in this conversation on 2026-10-02.','leadFaculty':'Dr. Martins Donbruce Idahosa','competencies':competencies,'sessions':sessions,'projects':[{'id':i,'title':t,'sessions':s,'data':'Fictional synthetic records only; no external organization data.'} for i,t,s in projects],'capstoneRubric':rubric,'rubricLevels':[{'level':'Not demonstrated','fraction':0},{'level':'Partial evidence','fraction':0.5},{'level':'Meets criterion with reproducible evidence','fraction':0.8},{'level':'Complete evidence including adversarial/failure cases','fraction':1}],'completion':{'sessionsRequired':20,'participation':'Attendance OR reviewed recording plus submitted lab, validated by faculty','allModuleAssessmentsPassed':True,'capstoneMinimum':70,'liveDefenseRequired':True,'finalKnowledgeCheckRequired':True,'finalAttempts':2,'remediation':'Free targeted remediation before attempt 2; third attempt requires staff review.'},'electives':['Reviewed AI-assisted coding','Hybrid visual and Python automation','Evaluated programmatic prompting','Agent interoperability research','Generative AI security'],'certificateValidity':'This certificate does not expire. The skills it covers evolve, so Scholarion offers refresher modules.','publicationBlockers':['Faculty content and assessment approval','Originality/accessibility review','Verified tool versions and educational licensing','Full notebooks, datasets, data cards and instructor editions','Final knowledge-check bank and remediation materials','Configured cohorts and policy Part E','Canvas/Cloud Lab/Zoom integration','Credential service and approved eligibility records'],'toolsDisclaimer':'Tool names describe intended teaching technologies; no affiliation is implied. No tool versions or licenses are verified by this package.'}
(ROOT/'dist/data/program15-curriculum.json').write_text(json.dumps(package,indent=2))
out=ROOT/'program15-review';out.mkdir(exist_ok=True)
for s in sessions:
 (out/(s['id']+'.txt')).write_text(f"{s['id']} — {s['title']}\nFaculty-review draft.\nOutcome: {s['outcome']}\nLab: {s['lab']}\nAssessment: {s['checkpoint']}\nEvidence: {', '.join(s['submission'])}\nMake-up: {s['makeup']}\n",encoding='utf-8')
(out/'PACKAGE.json').write_text(json.dumps(package,indent=2))
assert len(sessions)==20 and sum(s['liveMinutes'] for s in sessions)==3600
assert sum(r['points'] for r in rubric)==100
assert all(sum(a['minutes'] for a in s['agenda'])==180 for s in sessions)
print('Program 15: 20 session briefs, 5 competencies, 10 projects and 100-point capstone rubric validated.')
