"""Build trusted, deterministic practice notebooks; never execute learner input."""
import contextlib,io,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parent
LABS=[
('32-1','Bounded autonomy','Decide whether a proposed action needs a person. Keep unknown actions outside automatic execution.', 'def classify(action):\n    # TODO: reads are allowed; writes require review; everything else is denied\n    raise NotImplementedError', 'def classify(action):\n    return "allowed" if action == "read" else "review" if action == "write" else "denied"', 'assert classify("read")=="allowed"\nassert classify("write")=="review"\nassert classify("delete")=="denied"'),
('32-2','Evidence-driven reflection','Evaluate a draft claim against a supplied evidence dictionary. Reflection alone cannot manufacture missing evidence.', 'def verify_claim(claim, evidence):\n    # TODO: return verified only for an exact approved claim\n    raise NotImplementedError','def verify_claim(claim, evidence):\n    return "verified" if evidence.get(claim) is True else "unverified"','assert verify_claim("queue time fell", {"queue time fell":True})=="verified"\nassert verify_claim("guaranteed success", {})=="unverified"\nassert verify_claim("queue time fell", {"queue time fell":False})=="unverified"'),
('32-3','Typed tool boundaries','Validate a synthetic tool request before allowing it to reach a function. Treat booleans and missing values as invalid quantities.', 'def validate_quantity(value):\n    # TODO: accept integers from 1 through 10, otherwise raise ValueError\n    raise NotImplementedError','def validate_quantity(value):\n    if type(value) is not int or not 1 <= value <= 10:\n        raise ValueError("quantity rejected")\n    return value','assert validate_quantity(3)==3\nfor value in (True, 0, 11, "3", None):\n    try:\n        validate_quantity(value)\n        raise AssertionError("invalid input accepted")\n    except ValueError:\n        pass'),
('32-4','Dependency-aware planning','Order a small plan only when prerequisites are met. Reject cycles rather than guessing an execution order.', 'def order_plan(dependencies):\n    # TODO: topological order; raise ValueError for cycles or missing dependencies\n    raise NotImplementedError','def order_plan(dependencies):\n    pending={k:set(v) for k,v in dependencies.items()}\n    done=[]\n    while pending:\n        ready=sorted(k for k,v in pending.items() if v <= set(done))\n        if not ready:\n            raise ValueError("blocked or cyclic plan")\n        for key in ready:\n            done.append(key)\n            del pending[key]\n    return done','assert order_plan({"evaluate":["build"],"build":["scope"],"scope":[]})==["scope","build","evaluate"]\nfor plan in ({"a":["b"],"b":["a"]},{"a":["missing"]}):\n    try:\n        order_plan(plan)\n        raise AssertionError("blocked plan accepted")\n    except ValueError:\n        pass'),
('32-5','Collaborative error analysis','Combine specialist reports while keeping uncertainty visible. Do not turn majority agreement into verified evidence.', 'def summarize(reports):\n    # TODO: return passed/total counts and missing-evidence count\n    raise NotImplementedError','def summarize(reports):\n    return {"passed":sum(r.get("passed") is True for r in reports), "total":len(reports), "missing_evidence":sum(not r.get("evidence") for r in reports)}','assert summarize([{"passed":True,"evidence":"case-1"},{"passed":False}])=={"passed":1,"total":2,"missing_evidence":1}\nassert summarize([])=={"passed":0,"total":0,"missing_evidence":0}'),
('35','Approval-gated graph','Advance a synthetic workflow checkpoint only after explicit approval. A pending decision must preserve the review checkpoint.', 'def advance(state, approved=False):\n    # TODO: draft -> review; review -> complete only with exact True\n    raise NotImplementedError','def advance(state, approved=False):\n    if state == "draft": return "review"\n    if state == "review": return "complete" if approved is True else "review"\n    if state == "complete": return "complete"\n    raise ValueError("unknown checkpoint")','assert advance("draft")=="review"\nassert advance("review")=="review"\nassert advance("review",True)=="complete"\nassert advance("review","yes")=="review"'),
('36','Specialist-team handoff','Compare sequential and supervisor-reviewed handoff on synthetic reports. The reviewer requires both evidence and a completed analysis before a report is released.', 'def handoff(research, analysis, mode):\n    # TODO: sequential returns draft; hierarchical requires evidence and checked analysis\n    raise NotImplementedError','def handoff(research, analysis, mode):\n    if mode == "sequential": return "draft"\n    if mode == "hierarchical":\n        return "ready for human review" if research.get("evidence") and analysis.get("checked") is True else "revise"\n    raise ValueError("unknown mode")','assert handoff({}, {}, "sequential")=="draft"\nassert handoff({}, {"checked":True}, "hierarchical")=="revise"\nassert handoff({"evidence":"synthetic-source"},{"checked":True},"hierarchical")=="ready for human review"')]
def cell(kind,text,output=None):
 c={'cell_type':kind,'metadata':{},'source':text.splitlines(True)}
 if kind=='code':c.update(execution_count=1 if output is not None else None,outputs=[{'output_type':'stream','name':'stdout','text':[output]}] if output is not None else [])
 return c
public=ROOT/'dist/self-paced-practice';private=ROOT/'self-paced-review';public.mkdir(exist_ok=True);private.mkdir(exist_ok=True)
index=[]
for key,title,brief,starter,solution,tests in LABS:
 intro=f'# {title}\n\n{brief}\n\nPractice simulation only. No live AI, cloud execution, official grade or credential. Synthetic dictionaries are the entire dataset; no personal or externally licensed data. Python standard library only.\n\nAfter testing, explain one rejected input, one remaining limitation and the human decision boundary.'
 metadata={'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'},'language_info':{'name':'python','version':sys.version.split()[0]}}
 for edition,code in [('starter',starter),('executed',solution)]:
  output=None
  if edition=='executed':
   capture=io.StringIO()
   with contextlib.redirect_stdout(capture):exec(compile(code+'\n'+tests+'\nprint("All supplied practice checks passed")',key,'exec'),{})
   output=capture.getvalue()
  nb={'nbformat':4,'nbformat_minor':5,'metadata':metadata,'cells':[cell('markdown',intro),cell('code',code+'\n\n'+tests+'\nprint("All supplied practice checks passed")',output)]}
  (public if edition=='starter' else private).joinpath(key+'-'+edition+'.ipynb').write_text(json.dumps(nb,indent=2))
 index.append({'id':key,'title':title,'starter':'self-paced-practice/'+key+'-starter.ipynb','executedVerified':True,'runtime':sys.version.split()[0],'kind':'deterministic practice simulation'})
(public/'index.json').write_text(json.dumps(index,indent=2))
print(str(len(index))+' starter notebooks and private executed notebooks generated; all solution checks passed.')
