"""Build draft core programs, student exports and private instructor resources."""
from pathlib import Path
import json,csv,io,contextlib,sys,zipfile,html,math,re
from academy_topics import TOPICS,SEQUENCES,CONTEXTS
ROOT=Path(__file__).resolve().parent
OUT=ROOT/'dist'/'academy';OUT.mkdir(exist_ok=True)
catalog=json.loads((ROOT/'dist/data/programs.json').read_text(encoding='utf-8-sig'))
if isinstance(catalog,dict):catalog=catalog['programs']
FAMILIES={
'quality':('Keep rows with a numeric confidence between zero and one. Missing rows must not enter the accepted set.',"result = [r for r in rows if isinstance(r.get('confidence'), (int,float)) and 0 <= r['confidence'] <= 1]"),
'routing':('Map each ID to review if confidence is missing or below 0.8, otherwise ready_for_review. Neither route executes an action.',"result = {r['id']: ('review' if r['confidence'] is None or r['confidence'] < 0.8 else 'ready_for_review') for r in rows}"),
'evaluation':('Calculate reviewed count, total and review rate for each fictional queue; missing confidence requires review.',"result = {}\nfor group in sorted({r['queue'] for r in rows}):\n    subset = [r for r in rows if r['queue'] == group]\n    reviewed = sum(r['confidence'] is None or r['confidence'] < 0.8 for r in subset)\n    result[group] = {'reviewed':reviewed, 'total':len(subset), 'rate':reviewed/len(subset)}"),
'retrieval':("Rank three supplied snippets against 'approval required' by token overlap, then by ID for ties.","documents = {'D1':'human approval required before action','D2':'weekly aggregate counts only','D3':'approval required for sensitive update'}\nquery = set('approval required'.split())\nresult = sorted(documents, key=lambda k: (-len(query & set(documents[k].split())), k))"),
'workflow':('Map missing confidence to needs_data, below 0.8 to human_review, otherwise awaiting_approval. Never mark an action executed.',"result = {r['id']: ('needs_data' if r['confidence'] is None else 'human_review' if r['confidence'] < 0.8 else 'awaiting_approval') for r in rows}"),
'cost':('Compare 8 baseline minutes per record with 2 assisted minutes plus 7 review minutes for missing/low confidence, or 1 minute otherwise.',"baseline = len(rows)*8\nassisted = sum(2 + (7 if r['confidence'] is None or r['confidence'] < 0.8 else 1) for r in rows)\nresult = {'baseline_minutes':baseline,'assisted_minutes':assisted,'net_minutes_saved':baseline-assisted}"),
'reconcile':('Return IDs whose observed amount differs from expected by more than 0.01. These are review candidates, not proven misconduct.',"result = [r['id'] for r in rows if abs(r['observed']-r['expected']) > 0.01]")}
RUBRIC=[{'criterion':'Scope and assumptions','points':15,'outcome':'O1'},{'criterion':'Correctness and reproducibility','points':25,'outcome':'O2'},{'criterion':'Evaluation and failure analysis','points':25,'outcome':'O3'},{'criterion':'Privacy and human controls','points':20,'outcome':'O4'},{'criterion':'Communication and evidence','points':15,'outcome':'O5'}]
for r in RUBRIC:r['bands']={'Exemplary':'Full points: reproducible evidence, justified choices, limitations addressed.','Proficient':'75% of points: core requirement met; minor evidence gaps.','Developing':'50% of points: partial implementation or weak justification.','Insufficient':'0 points: missing evidence or unsafe result.'}
def write(path,text):path.parent.mkdir(parents=True,exist_ok=True);path.write_text(text,encoding='utf-8')
def jsave(path,obj):write(path,json.dumps(obj,indent=2,ensure_ascii=False))
def synthetic(pid,index,n=18):return [{'id':f'P{pid}M{index}R{i:03d}','queue':['North','South','Central'][i%3],'confidence':None if i%7==0 else round((i%10)/10,1),'expected':100+i*7,'observed':100+i*7+(3 if i%5==0 else 0)} for i in range(n)]
def notebook(title,rows,task,code,execute=False):
    body='rows = '+repr(rows)+'\n'+code+'\nprint(result)\n';outputs=[]
    if execute:
        stream=io.StringIO()
        with contextlib.redirect_stdout(stream):exec(compile(body,'<draft-notebook>','exec'),{})
        outputs=[{'output_type':'stream','name':'stdout','text':stream.getvalue().splitlines(True)}]
    return {'nbformat':4,'nbformat_minor':5,'metadata':{'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'},'language_info':{'name':'python','version':sys.version.split()[0]}},'cells':[{'id':'instructions','cell_type':'markdown','metadata':{},'source':[f'# {title}\n\nSynthetic educational simulation; no live model or real personal data.\n\n{task}']},{'id':'practice','cell_type':'code','metadata':{},'source':body.splitlines(True),'execution_count':1 if execute else None,'outputs':outputs}]}
programs=[];executed=0
for pid in [2,1,7,6,5,8,9,3,4,10,11]:
    original=next(x for x in catalog if x['id']==pid);context,portfolio,prereq=CONTEXTS[pid];keys=SEQUENCES[pid].split()
    base=OUT/f'program-{pid}';student=base/'student';instructor=ROOT/'instructor-packages'/f'program-{pid}'
    p={**original,'issuer':'Scholarion Academy','status':'Draft — academic review required','audience':context,'weeklyHours':'6–10' if pid in [1,2,3,4] else '4–6','prerequisites':prereq,'delivery':'Self-paced draft modules with proposed weekend workshops, peer discussion and office hours; no cohort scheduled.','outcomes':[f'O1: Map decision boundaries and evidence requirements for {context}.',f'O2: Construct and explain a bounded prototype for {context}.','O3: Evaluate ordinary, ambiguous and adversarial cases against a baseline.','O4: Demonstrate privacy minimization, human approval and recoverable failure.',f'O5: Defend a {portfolio} portfolio with reproducible evidence and limitations.'],'modules':[],'rubric':RUBRIC,'scheduleNote':'Two 10-module blocks need pacing approval within the advertised duration; no automatic workload compression is approved.' if pid in [1,2] else 'Proposed sequence; dates and pacing require approval.','credential':{'type':'Certificate of Completion','issuer':'Scholarion Academy','eligible':False,'requiredCourseIds':[],'rule':'Every approved required course at C or better. Required-course list and final grading policy TBC.','sourceDraftRules':'Historical source additionally proposes 70% overall, all labs, capstone pass, and 80% participation/approved alternative. These are draft proposals, not activated issuance rules.'},'career':{'portfolio':portfolio,'services':['Portfolio review','Resume evidence workshop','Interview practice'],'resumePrompt':'Describe your contribution, synthetic setting, evaluation and measured results. Do not imply production deployment.','interviewPrompt':'Explain one failure, how you detected it, and why a human remained accountable.','disclaimer':'Related task skills, not a job, salary or placement guarantee.'},'qualityGates':{'structure':'automated check','syntheticData':'generated','executedSimulationNotebooks':'verified locally','SMEReview':'pending','independentInstructionalReview':'pending','originalityReview':'pending','fullAccessibilityAudit':'pending','recordedCaptionedMedia':'pending','liveProviderLabsAndLicenses':'pending','authenticatedLMSAndLTI':'pending','commonCartridgeValidation':'pending','productionPublication':'blocked'}}
    p['blocks']=[{'id':f'P{pid}-B{b+1}','modules':list(range(b*10+1,(b+1)*10+1)),'status':'Draft syllabus'} for b in range(2)] if pid in [1,2,3] else [{'id':f'P{pid}-B1','modules':list(range(1,min(10,len(keys))+1)),'status':'Draft syllabus'}]
    capindex=0
    for i,key in enumerate(keys,1):
        t=TOPICS[key];rows=synthetic(pid,i);task,solution=FAMILIES[t['family']];title=t['title']
        if key=='capstone':
            title=['Capstone scope and baseline','Capstone implementation clinic','Capstone evaluation clinic','Capstone peer review','Capstone defense'][capindex%5];capindex+=1
        objective=p['outcomes'][(i-1)%5]
        quizzes=[{'id':f'P{pid}M{i}Q1','prompt':t['question'],'choices':[t['correct'],t['wrong'],'Skip review and trust the output.'],'correct':0,'explanation':t['lesson'],'outcomes':['O1','O4']},{'id':f'P{pid}M{i}Q2','prompt':f'Your team supporting {context} cannot reproduce a result. What next?','choices':['Publish because the report looks complete.','Reproduce the inputs, versions and checks before accepting the claim.','Remove failing examples.'],'correct':1,'explanation':'Keep failures visible. A claim needs reproducible evidence.','outcomes':['O3','O5']},{'id':f'P{pid}M{i}Q3','prompt':f'Which artifact best demonstrates {title.lower()}?','choices':[t['task']+' Include results and limitations.','A screenshot with no inputs or explanation.','An assertion of perfect accuracy.'],'correct':0,'explanation':'A concrete artifact and observed evidence support review.','outcomes':['O2','O5']}]
        activity={'title':title+' — applied workshop','objective':objective,'overview':f'You support {context}. {t["task"]}','steps':[{'title':'Concept setup · 10 minutes','text':t['lesson']},{'title':'Implementation · 20 minutes','text':task+' Open the starter notebook or visual workflow simulator.'},{'title':'Task · 20 minutes','text':t['task']+' Record a normal, missing-input and human-review case.'},{'title':'Research and discussion · 15 minutes','text':'Compare with a peer, cite your reading and identify a failure condition.'},{'title':'Wrap-up · 5 minutes','text':'Explain why a simulation is not a production-ready system; name the accountable owner.'}],'reflection':['What evidence changes your decision?','Which error is more costly here?','What information can you avoid retaining?'],'submission':'Draft cohort policy: 2–3-page APA-style paper with relevant code, output screenshots and citations. Word/PDF upload and Sunday 11:59 PM deadline need a scheduled cohort; no live deadline is set.','integrity':'AI coaching on concepts and ungraded practice is allowed with disclosure. Graded reasoning must be your own.'}
        m={'id':f'P{pid}-M{i:02d}','number':i,'title':title,'topic':key,'family':t['family'],'lesson':t['lesson'],'outcomes':['O1','O2','O3','O4','O5'],'activity':activity,'labTask':task,'miniLabs':[{'title':'Missing-input stress test','task':'Replace every fourth confidence with None. Re-run and explain the changed results.'},{'title':'Scale and subgroup check','task':'Use the 60-row assignment dataset; compare queues and state a sampling limitation.'}],'readings':[{'title':'Python CSV reference','url':'https://docs.python.org/3.12/library/csv.html'},{'title':'Python test framework reference','url':'https://docs.python.org/3.12/library/unittest.html'},{'title':'NIST AI risk framework overview','url':'https://www.nist.gov/itl/ai-risk-management-framework'}],'quiz':quizzes,'liveSession':'Compare two approaches to '+title.lower()+' and defend the review boundary.','announcement':f'Module {i}: {title}. Review the objective, run practice cases and bring a failure to discussion. Cohort dates pending.','prerequisite':f'P{pid}-M{i-1:02d}' if i>1 else None,'masteryPath':{'remediation':'Re-read the concept, repeat the missing-input task and explain the mistake before retrying.','enrichment':'Change an assumption, create a counterexample and compare error rates.'},'path':f'academy/program-{pid}/student/module-{i:02d}'}
        m['proposedWeek']=math.ceil(i*int(re.search(r'\d+',p['length']).group())/len(keys))
        if t['family']=='retrieval':
            m['miniLabs']=[{'title':'Abstention test','task':"Change the query to 'unicorn policy'. Return no ranked result when every overlap score is zero."},{'title':'Evidence-sensitive ranking','task':"Change the query to 'sensitive update'. Explain why D3 should rank first and why its rank does not authorize an update."}]
        folder=student/f'module-{i:02d}';teach=instructor/f'module-{i:02d}';folder.mkdir(parents=True,exist_ok=True);big=synthetic(pid,i,60)
        for filename,data in [('dataset.csv',rows),('assignment-dataset.csv',big)]:
            with (folder/filename).open('w',newline='',encoding='utf-8') as f:w=csv.DictWriter(f,fieldnames=data[0]);w.writeheader();w.writerows(data)
        jsave(folder/'data-card.json',{'source':'Deterministic synthetic generator build_academy.py','license':'CC0-1.0 for synthetic rows','fields':{'id':'Invented record ID','queue':'Fictional group','confidence':'Artificial, uncalibrated score or missing','expected':'Synthetic amount','observed':'Synthetic amount with seeded mismatch'},'intendedUse':'Education only','limitations':['Periodic artificial patterns','Not representative of real people','No clinical, lending or investment use'],'rows':18,'assignmentRows':60})
        for label,data in [('starter',rows),('mini-1-starter',[{**r,'confidence':None if j%4==0 else r['confidence']} for j,r in enumerate(rows)]),('mini-2-starter',big)]:
            currentTask=task;currentSolution=solution
            if t['family']=='retrieval' and label=='mini-1-starter':
                currentTask=m['miniLabs'][0]['task'];currentSolution=solution.replace("'approval required'.split()","'unicorn policy'.split()")+"\nresult = [key for key in result if query & set(documents[key].split())]"
            if t['family']=='retrieval' and label=='mini-2-starter':
                currentTask=m['miniLabs'][1]['task'];currentSolution=solution.replace("'approval required'.split()","'sensitive update'.split()")
            jsave(folder/(label+'.ipynb'),notebook(title,data,currentTask,'# TODO: implement the task using rows or the source snippets.\nresult = None'))
            jsave(teach/(label.replace('starter','solution')+'.ipynb'),notebook(title,data,currentTask,currentSolution,True));executed+=1
        write(folder/'activity.md','# '+activity['title']+'\n\n'+activity['overview']+'\n\n'+'\n\n'.join('## '+x['title']+'\n'+x['text'] for x in activity['steps'])+'\n\n## Submission\n'+activity['submission']+'\n\n## Integrity\n'+activity['integrity'])
        write(folder/'walkthrough.md',f'# {title}: visual walkthrough\n\nOffline rules simulation, not a commercial AI platform.\n\n1. Open this module in Scholarion and select Visual workflow lab.\n2. Set review threshold to 0.8.\n3. Keep missing input routed to Needs data.\n4. Run the synthetic cases. No external action executes.\n5. Compare with your task: {t["task"]}\n6. Try 0.6 and export results.\n7. Record the changed decisions and human checkpoint.\n\nPlatform-specific licensed builds and screenshots remain pending.')
        write(teach/'reference-build.md','# Reference build\n\nThreshold 0.8; missing input needs_data; low score human_review; other scores awaiting_approval. No action executes.\n\nFor this module’s numerical output see the executed solution notebook.\n\n'+t['correct']+'\n\n'+t['lesson'])
        jsave(teach/'answer-key.json',quizzes)
        write(teach/'guide.md',f'# Instructor guide: {title}\n\nObjective: {objective}\n\nTiming: 10-minute setup, 20-minute implementation, 20-minute challenge, 15-minute critique, 5-minute wrap-up.\n\nEmphasize: {t["correct"]}\n\nCommon mistake: {t["wrong"]}. Ask which assumption failed.\n\nWorked interpretation: {t["lesson"]}\n\nDiscussion: post one failure and critique one peer with evidence.\n\nDo not treat a rules simulation as a live model or production service. Review the claim against reproduced outputs.')
        slides=[('Decision to make',activity['overview']),('Core concept',t['lesson']),('Practice contract',task),('Evidence and boundary','Show normal, missing and uncertain cases. No real data or external actions.'),('Review and reflect',t['correct'])]
        write(folder/'slides.html','<!doctype html><html lang="en"><meta charset="utf-8"><title>'+html.escape(title)+'</title><style>body{font:20px Arial;color:#12354b;margin:40px}section{padding:40px;border:1px solid #ccc;min-height:250px;margin:20px 0}p{line-height:1.6}</style>'+''.join('<section><h1>'+html.escape(a)+'</h1><p>'+html.escape(b)+'</p></section>' for a,b in slides))
        write(folder/'lecture-script.txt','Draft transcript; recording and synchronized captions pending.\n\n'+'\n\n'.join(a+'\n'+b for a,b in slides))
        p['modules'].append(m)
    assessments=[]
    for block in p['blocks']:
        nums=block['modules'];scaled=pid==7
        counts=[('Assignment',3 if scaled else 5),('Lab',2 if scaled else 3),('Project',1 if scaled else 2),('Quiz',6 if scaled else 8),('Final practical' if scaled else 'Final defense',1)]+([] if scaled else [('Midterm',1)])
        for kind,count in counts:
            for j in range(count):
                num=nums[min(len(nums)-1,math.ceil((j+1)*len(nums)/count)-1)];m=p['modules'][num-1]
                assessments.append({'id':f'{block["id"]}-{kind.replace(" ","-")}-{j+1}','type':kind,'module':num,'outcomes':m['outcomes'],'brief':m['activity']['overview']+' Use the larger dataset; document assumptions, method, checks, output and reflection.','steps':['Define scope and boundaries','Inspect data card and dataset','Establish a baseline','Build a rule or design','Test missing and adversarial cases','Interpret results and cite sources'],'rubric':RUBRIC,'aiPolicy':'Coaching with disclosure; assessed reasoning must be your own.'})
    p['assessments']=assessments
    p['capstonePackage']={'brief':p['capstone'],'milestones':[{'name':'Scope and baseline','deliverable':'Boundary, data card, baseline and success criteria.'},{'name':'Prototype and controls','deliverable':'Runnable or visual prototype, source log and approval path.'},{'name':'Evaluation and peer review','deliverable':'Held-out cases, failures, peer critique and revisions.'},{'name':'Defense and handover','deliverable':'Five-minute evidence demo, five-minute questions, runbook and limitations.'}],'rubric':RUBRIC,'exemplar':'A fictional approval queue retains missing scores, routes uncertainty to review and never executes updates. Its evidence pack records input versions, thresholds, subgroup counts, failed cases and a rollback owner. Adapt this scaffold to the program brief. This is not a finished capstone solution.','peerReview':'A peer challenges an unsupported claim and repeats one test; the author documents the response.','status':'Draft brief; finished program-specific exemplars require SME authoring.'}
    p['evaluationPlan']={'pre':'Explain a bounded workflow before instruction and attempt the first practice pool.','post':'Use unseen synthetic cases and compare outcome-aligned rubric scores.','survey':['What was unclear?','Which failure changed your design?','Was the workload feasible?'],'analytics':'Local practice attempts and module checkpoints, not official grades.'}
    p['transferPolicy']='No automatic credit. Map outcomes and assessed evidence; an educator approves equivalence and prevents duplicate credit. Dependencies #1–#14 remain TBC.'
    jsave(student/'syllabus.json',{k:v for k,v in p.items() if k!='modules'});jsave(student/'assessment-briefs.json',assessments);jsave(student/'capstone.json',p['capstonePackage']);jsave(instructor/'full-program.json',p)
    studentp=json.loads(json.dumps(p))
    for m in studentp['modules']:
        for q in m['quiz']:q.pop('correct');q.pop('explanation')
    jsave(student/'program.json',studentp)
    write(student/'README.txt','Scholarion Academy DRAFT student package. Synthetic offline practice. Instructor resources are outside the public site.\nNot a validated Common Cartridge or production Cloud Lab deployment.\nPython tested: '+sys.version.split()[0]+'; standard library only. Colab/LTI execution not tested.\n')
    with zipfile.ZipFile(base/'student-package.zip','w',zipfile.ZIP_DEFLATED) as z:
        for f in student.rglob('*'):
            if f.is_file():z.write(f,f.relative_to(student))
    with zipfile.ZipFile(instructor/'instructor-package.zip','w',zipfile.ZIP_DEFLATED) as z:
        for f in instructor.rglob('*'):
            if f.is_file() and f.suffix!='.zip':z.write(f,f.relative_to(instructor))
    programs.append(p)
jsave(OUT/'programs.json',programs)
write(ROOT/'dist/academy-data.js','const academyPrograms = '+json.dumps(programs,ensure_ascii=False)+';\n')
manifest={'programs':len(programs),'modules':sum(len(p['modules']) for p in programs),'executedNotebooks':executed,'python':sys.version.split()[0],'publication':'blocked','limitations':['Academic content needs independent review','Notebooks are deterministic simulations, not live framework labs','Recorded media, screenshots, Common Cartridge and LTI pending','Practice checkpoints never update grades or eligibility']}
jsave(OUT/'build-report.json',manifest)
print(json.dumps(manifest,indent=2))
