from pathlib import Path
p=Path('site/dist/academy.js');s=p.read_text(encoding='utf-8-sig')
s=s.replace("const academyProgram=id=>", "let academyLabCsv='';\nconst academyProgram=id=>")
s=s.replace('id="academy-lab-form"><label>', 'id="academy-lab-form" data-family="${m.family}">${m.family===\'retrieval\'?\'<label>Evidence query<input name="query" value="approval required" required></label>\':\'\'}<label>')
a=s.index("const rows=Array.from({length:18}",s.index("if(f.id==='academy-lab-form')"))
b=s.index("}});",a)
s=s[:a]+'''const rows=Array.from({length:18},(_,i)=>({id:'R'+String(i).padStart(3,'0'),queue:['North','South','Central'][i%3],score:i%7===0?null:(i%10)/10,expected:100+i*7,observed:100+i*7+(i%5===0?3:0)}));let headers=['Synthetic ID','Score','Next state'],data=rows.map(r=>[r.id,r.score??'Missing',r.score===null?'Needs data':r.score<threshold?'Human review':'Awaiting approval']);const family=f.dataset.family;if(family==='retrieval'){const docs=[['D1','human approval required before action'],['D2','weekly aggregate counts only'],['D3','approval required for sensitive update']];const query=new Set(String(new FormData(f).get('query')).toLowerCase().match(/[a-z]+/g)||[]);headers=['Source','Text','Token overlap'];data=docs.map(([id,text])=>[id,text,[...new Set(text.split(' '))].filter(w=>query.has(w)).length]).filter(r=>r[2]>0).sort((a,b)=>b[2]-a[2]||a[0].localeCompare(b[0]));}if(family==='quality'){headers=['Synthetic ID','Confidence','Validation'];data=rows.map(r=>[r.id,r.score??'Missing',r.score===null?'Rejected: missing confidence':'Valid numeric score']);}if(family==='reconcile'){headers=['Synthetic ID','Expected','Observed','Review'];data=rows.map(r=>[r.id,r.expected,r.observed,Math.abs(r.expected-r.observed)>.01?'Exception':'Within tolerance']);}if(family==='cost'){const assisted=rows.reduce((n,r)=>n+2+(r.score===null||r.score<threshold?7:1),0);headers=['Baseline minutes','Assisted and review minutes','Net saved'];data=[[rows.length*8,assisted,rows.length*8-assisted]];}if(family==='evaluation'){headers=['Queue','Review count','Total','Rate'];data=['North','South','Central'].map(q=>{const xs=rows.filter(r=>r.queue===q),n=xs.filter(r=>r.score===null||r.score<threshold).length;return [q,n,xs.length,(n/xs.length).toFixed(3)];});}academyLabCsv=[headers,...data].map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\\n');document.getElementById('academy-lab-output').innerHTML='<div class="table-scroll"><table><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+data.map(r=>'<tr>'+r.map(v=>'<td>'+esc(String(v))+'</td>').join('')+'</tr>').join('')+'</tbody></table></div><p>'+(data.length?'Synthetic simulation only. No actions executed.':'No supporting source found. Abstain rather than invent evidence.')+'</p><button class="button secondary" data-academy-export="result">Export result table</button>';''' +s[b:]
a=s.index("if(t.dataset.academyExport){")
b=s.index("}});",a)
s=s[:a]+"if(t.dataset.academyExport){download('synthetic-lab-results.csv',academyLabCsv,'text/csv');"+s[b:]
s=s.replace('<p>${done?', '<p>Proposed week ${m.proposedWeek} · ${done?')
s=s.replace("${btn('Create badge','#badge-generator',true)}", "${btn('Create badge','#badge-generator',true)}")
s=s.replace("heading(p.title,p.status,btn('Create badge','#badge-generator',true))", "heading(p.title,p.status,`<button class=\"button secondary\" data-academy-badge=\"${p.id}\">Create badge</button>`)")
s=s.replace("document.addEventListener('click',e=>{const t=e.target.closest('[data-academy-complete]", "document.addEventListener('click',e=>{const badge=e.target.closest('[data-academy-badge]');if(badge){const p=academyProgram(badge.dataset.academyBadge);badgeConfig={id:p.id,title:p.title,type:'Certificate',style:'ribbon'};location.hash='badge-generator';return;}const t=e.target.closest('[data-academy-complete]")
p.write_text(s,encoding='utf-8')
